// Generated by unRap v1.06 by Kegetys

class RscDisplayMPPlayers : RscStandardDisplay {
	class controlsBackground {
		class Mainback : CA_Mainback {
			moving = 1;
			x = 0.022055;
			y = 0.05882;
			w = 0.95589;
			h = 0.88236;
			colorbackground[] = {0.6, 0.6, 0.6, 0.4};
		};
		
		class Missionback : CA_Back {
			x = 0.025;
			y = 0.11;
			w = 0.95;
			h = 0.035;
		};
		
		class Playersback : CA_Back {
			x = 0.025;
			y = 0.15;
			w = 0.25;
			h = 0.72;
		};
		
		class Squadback : CA_Back {
			x = 0.28;
			y = 0.15;
			w = 0.7;
			h = 0.72;
		};
		
		class FilterTitleBack : CA_Title_Back {
			x = 0.029408;
			y = 0.068624;
			w = 0.941184;
			h = 0.039216;
		};
		
		class Logo : CA_Logo_Small {
			x = 0.79412;
			y = 0.0205844;
		};
	};
	
	class controls {
		delete Title;
		delete TextMission;
		delete ValueMission;
		delete TextIsland;
		delete ValueIsland;
		delete TextTime;
		delete ValueTime;
		delete ValueRest;
		delete TextPlayers;
		delete ValuePlayers;
		delete TextPlayer;
		delete ValuePlayer;
		delete TextPlayerName;
		delete ValuePlayerName;
		delete TextPlayerMail;
		delete ValuePlayerMail;
		delete TextPlayerICQ;
		delete ValuePlayerICQ;
		delete TextPlayerRemark;
		delete ValuePlayerRemark;
		delete PingTitle;
		delete PingMinValue;
		delete PingAvgValue;
		delete PingMaxValue;
		delete BandwidthTitle;
		delete BandwidthMinValue;
		delete BandwidthAvgValue;
		delete BandwidthMaxValue;
		delete DesyncTitle;
		delete DesyncValue;
		delete TextSquad;
		delete ValueSquad;
		delete TextSquadName;
		delete ValueSquadName;
		delete TextSquadId;
		delete ValueSquadId;
		delete TextSquadMail;
		delete ValueSquadMail;
		delete TextSquadWeb;
		delete ValueSquadWeb;
		delete TextSquadPicture;
		delete ValueSquadPicture;
		delete TextSquadTitle;
		delete ValueSquadTitle;
		delete B_Cancel;
		delete B_Ban;
		delete B_Mute;
		delete B_KickOff;
		
		class CA_PlayersTitle : CA_Title {
			text = $STR_DISP_MP_PLAYERS_TITLE;
			x = 0.025;
			y = 0.055;
			w = 0.12;
			colortext[] = {0.95, 0.95, 0.95, 1};
		};
		
		class CA_TextMission : RscText {
			x = 0.025;
			y = 0.11;
			w = 0.12;
			text = $STR_DISP_SRVSETUP_NAME;
		};
		
		class CA_ValueMission : RscText {
			idc = 116;
			x = 0.145;
			y = 0.11;
			w = 0.23;
		};
		
		class CA_TextIsland : RscText {
			x = 0.4;
			y = 0.11;
			w = 0.1;
			text = $STR_DISP_SRVSETUP_ISLAND;
		};
		
		class CA_ValueIsland : RscText {
			idc = 117;
			x = 0.5;
			y = 0.11;
			w = 0.2;
		};
		
		class CA_TextTime : RscText {
			x = 0.625;
			y = 0.11;
			w = 0.1;
			text = $STR_DISP_MP_PL_TIME;
		};
		
		class CA_ValueTime : RscText {
			idc = 118;
			x = 0.725;
			y = 0.11;
			w = 0.1;
		};
		
		class CA_ValueRest : RscText {
			idc = 126;
			x = 0.825;
			y = 0.11;
			w = 0.15;
		};
		
		class CA_TextPlayers : RscText {
			x = 0.025;
			y = 0.15;
			w = 0.25;
			text = $STR_DISP_MP_PLAYERS;
		};
		
		class CA_ValuePlayers : RscListBox {
			idc = 101;
			onLBSelChanged = "_this call compile preprocessfile ""\A3\ui_f\scripts\lbColor.sqf"";";
			x = 0.025;
			y = 0.2;
			w = 0.25;
			h = 0.65;
			rows = 18.5;
		};
		
		class CA_TextPlayer : RscText {
			x = 0.3;
			y = 0.15;
			w = 0.15;
			text = $STR_DISP_MP_PL;
		};
		
		class CA_ValuePlayer : RscText {
			idc = 102;
			x = 0.45;
			y = 0.15;
			w = 0.525;
		};
		
		class CA_TextPlayerName : RscText {
			x = 0.325;
			y = 0.18;
			w = 0.125;
			text = $STR_DISP_MP_PL_NAME;
		};
		
		class CA_ValuePlayerName : RscText {
			idc = 103;
			x = 0.45;
			y = 0.18;
			w = 0.525;
		};
		
		class CA_TextPlayerMail : RscText {
			x = 0.325;
			y = 0.21;
			w = 0.125;
			text = $STR_DISP_MP_PL_MAIL;
		};
		
		class CA_ValuePlayerMail : RscText {
			idc = 104;
			x = 0.45;
			y = 0.21;
			w = 0.525;
		};
		
		class CA_TextPlayerICQ : RscText {
			x = 0.325;
			y = 0.24;
			w = 0.125;
			text = $STR_DISP_MP_PL_ICQ;
		};
		
		class CA_ValuePlayerICQ : RscText {
			idc = 105;
			x = 0.45;
			y = 0.24;
			w = 0.525;
		};
		
		class CA_TextPlayerRemark : RscText {
			x = 0.325;
			y = 0.27;
			w = 0.125;
			text = $STR_DISP_MP_PL_REMARK;
		};
		
		class CA_ValuePlayerRemark : RscText {
			idc = 106;
			x = 0.45;
			y = 0.27;
			w = 0.525;
			h = 0.145;
			style = 16;
			lines = 3;
			lineSpacing = 0.01;
		};
		
		class CA_PingTitle : RscText {
			x = 0.325;
			y = 0.42;
			w = 0.15;
			text = $STR_DISP_MP_PING;
		};
		
		class CA_PingMinValue : RscText {
			idc = 119;
			x = 0.48;
			y = 0.42;
			w = 0.07;
		};
		
		class CA_PingAvgValue : RscText {
			idc = 120;
			x = 0.58;
			y = 0.42;
			w = 0.07;
		};
		
		class CA_PingMaxValue : RscText {
			idc = 121;
			x = 0.68;
			y = 0.42;
			w = 0.07;
		};
		
		class CA_BandwidthTitle : RscText {
			x = 0.325;
			y = 0.45;
			w = 0.15;
			text = $STR_DISP_MP_BANDWIDTH;
		};
		
		class CA_BandwidthMinValue : RscText {
			idc = 122;
			x = 0.48;
			y = 0.45;
			w = 0.07;
		};
		
		class CA_BandwidthAvgValue : RscText {
			idc = 123;
			x = 0.58;
			y = 0.45;
			w = 0.07;
		};
		
		class CA_BandwidthMaxValue : RscText {
			idc = 124;
			x = 0.68;
			y = 0.45;
			w = 0.07;
		};
		
		class CA_DesyncTitle : RscText {
			x = 0.325;
			y = 0.48;
			w = 0.15;
			text = $STR_DISP_MP_DESYNC;
		};
		
		class CA_DesyncValue : RscText {
			idc = 125;
			x = 0.48;
			y = 0.48;
			w = 0.07;
		};
		
		class CA_TextSquad : RscText {
			x = 0.3;
			y = 0.54;
			w = 0.15;
			text = $STR_DISP_MP_SQ;
		};
		
		class CA_ValueSquad : RscText {
			idc = 107;
			x = 0.45;
			y = 0.54;
			w = 0.525;
		};
		
		class CA_TextSquadName : RscText {
			x = 0.325;
			y = 0.57;
			w = 0.125;
			text = $STR_DISP_MP_SQ_NAME;
		};
		
		class CA_ValueSquadName : RscText {
			idc = 108;
			x = 0.45;
			y = 0.57;
			w = 0.525;
		};
		
		class CA_TextSquadId : RscText {
			x = 0.325;
			y = 0.6;
			w = 0.125;
			text = $STR_DISP_MP_SQ_ID;
		};
		
		class CA_ValueSquadId : RscText {
			idc = 109;
			x = 0.45;
			y = 0.6;
			w = 0.525;
		};
		
		class CA_TextSquadMail : RscText {
			x = 0.325;
			y = 0.63;
			w = 0.125;
			text = $STR_DISP_MP_SQ_MAIL;
		};
		
		class CA_ValueSquadMail : RscText {
			idc = 110;
			x = 0.45;
			y = 0.63;
			w = 0.525;
		};
		
		class CA_TextSquadWeb : RscText {
			x = 0.325;
			y = 0.66;
			w = 0.125;
			text = $STR_DISP_MP_SQ_WEB;
		};
		
		class CA_ValueSquadWeb : RscText {
			idc = 111;
			x = 0.45;
			y = 0.66;
			w = 0.525;
		};
		
		class CA_TextSquadPicture : RscText {
			x = 0.325;
			y = 0.69;
			w = 0.125;
			text = $STR_DISP_MP_SQ_PICTURE;
		};
		
		class CA_ValueSquadPicture : RscPicture {
			idc = 112;
			style = 48;
			x = 0.45;
			y = 0.69;
			w = 0.093;
			h = 0.124;
		};
		
		class CA_TextSquadTitle : RscText {
			x = 0.325;
			y = 0.82;
			w = 0.125;
			text = $STR_DISP_MP_SQ_TITLE;
		};
		
		class CA_ValueSquadTitle : RscText {
			idc = 113;
			x = 0.45;
			y = 0.82;
			w = 0.525;
		};
		
		class CA_B_Mute : CA_RscButton_dialog {
			idc = 127;
			x = 0.28;
			y = 0.9;
			borderSize = 0.0;
			text = $STR_DIK_MUTE;
		};
		
		delete CA_B_KickOff;
		/*
		class CA_B_KickOff : CA_B_Mute {
			idc = 114;
			x = 0.28;
			y = 0.9;
			borderSize = 0.0;
			text = $STR_DISP_MP_KICKOFF;
		};
		*/
		
		delete CA_B_Ban;
		/*
		class CA_B_Ban : CA_B_KickOff {
			idc = 115;
			x = 0.438;
			borderSize = 0.0;
			text = $STR_DISP_MP_BAN;
		};
		*/
		
		class CA_B_Cancel : CA_RscButton_dialog {
			idc = 2;
			x = 0.828;
			y = 0.9;
			default = 1;
			text = $STR_DISP_CLOSE;
		};
	};
};
