// Generated by unRap v1.06 by Kegetys

class RscDisplayNewUser : RscStandardDisplay {
	onLoad = "[""onLoad"",_this,""RscDisplayNewUser"",'GUI'] call compile preprocessfilelinenumbers ""A3\ui_f\scripts\initDisplay.sqf""";
	onUnload = "[""onUnload"",_this,""RscDisplayNewUser"",'GUI'] call compile preprocessfilelinenumbers ""A3\ui_f\scripts\initDisplay.sqf""";
	
	class controlsBackground {
		delete Vignette;
		delete TileGroup;
		
		class Mainback : RscPicture {
			idc = 2310;
			text = "\breakingpoint_ui\loading\main_title_01.jpg";
			x = 0 * safezoneW + safezoneX;
			y = 0 * safezoneH + safezoneY;
			w = 1 * safezoneW;
			h = 1 * safezoneH;
		};
		
		class BcgCommon : RscBackgroundGUI {
			idc = 11000;
			backgroundType = 0;
			x = "1 * 			(		((safezoneW / safezoneH) min 1.2) / 32) + 			(safezoneX)";
			y = "1 * 			(		(		((safezoneW / safezoneH) min 1.2) / 1.2) / 20) + 			(safezoneY + safezoneH - 		(		((safezoneW / safezoneH) min 1.2) / 1.2))";
			w = "10 * 			(		((safezoneW / safezoneH) min 1.2) / 32)";
			h = "18 * 			(		(		((safezoneW / safezoneH) min 1.2) / 1.2) / 20)";
		};
		
		class BcgCommonLeft : RscBackgroundGUILeft {
			idc = 11200;
			backgroundType = 0;
			x = "1 * 			(		((safezoneW / safezoneH) min 1.2) / 32) + 			(safezoneX)";
			y = "1 * 			(		(		((safezoneW / safezoneH) min 1.2) / 1.2) / 20) + 			(safezoneY + safezoneH - 		(		((safezoneW / safezoneH) min 1.2) / 1.2))";
			w = "10 * 			(		((safezoneW / safezoneH) min 1.2) / 32)";
			h = "18 * 			(		(		((safezoneW / safezoneH) min 1.2) / 1.2) / 20)";
		};
		
		class BcgCommonRight : RscBackgroundGUIRight {
			idc = 11201;
			backgroundType = 0;
			x = "1 * 			(		((safezoneW / safezoneH) min 1.2) / 32) + 			(safezoneX)";
			y = "1 * 			(		(		((safezoneW / safezoneH) min 1.2) / 1.2) / 20) + 			(safezoneY + safezoneH - 		(		((safezoneW / safezoneH) min 1.2) / 1.2))";
			w = "10 * 			(		((safezoneW / safezoneH) min 1.2) / 32)";
			h = "18 * 			(		(		((safezoneW / safezoneH) min 1.2) / 1.2) / 20)";
		};
		
		class BcgCommonBottom : RscBackgroundGUIBottom {
			idc = 11001;
			backgroundType = 0;
			x = "1 * 			(		((safezoneW / safezoneH) min 1.2) / 32) + 			(safezoneX)";
			y = "1 * 			(		(		((safezoneW / safezoneH) min 1.2) / 1.2) / 20) + 			(safezoneY + safezoneH - 		(		((safezoneW / safezoneH) min 1.2) / 1.2)) +  			18 * 			(		(		((safezoneW / safezoneH) min 1.2) / 1.2) / 20) 		 - (1 * 			(		(		((safezoneW / safezoneH) min 1.2) / 1.2) / 20))";
			w = "10 * 			(		((safezoneW / safezoneH) min 1.2) / 32)";
			h = "1 * 			(		(		((safezoneW / safezoneH) min 1.2) / 1.2) / 20)";
		};
		
		class BcgCommonTop : RscBackgroundGUITop {
			idc = 11002;
			backgroundType = 0;
			x = "1 * 			(		((safezoneW / safezoneH) min 1.2) / 32) + 			(safezoneX)";
			y = "1 * 			(		(		((safezoneW / safezoneH) min 1.2) / 1.2) / 20) + 			(safezoneY + safezoneH - 		(		((safezoneW / safezoneH) min 1.2) / 1.2))";
			w = "10 * 			(		((safezoneW / safezoneH) min 1.2) / 32)";
			h = "1 * 			(		(		((safezoneW / safezoneH) min 1.2) / 1.2) / 20)";
		};
		
		class BcgCommon1 : RscBackgroundGUI {
			idc = 110001;
			backgroundType = 1;
			x = "11 * 			(		((safezoneW / safezoneH) min 1.2) / 32) + 			(safezoneX)";
			y = "1 * 			(		(		((safezoneW / safezoneH) min 1.2) / 1.2) / 20) + 			(safezoneY + safezoneH - 		(		((safezoneW / safezoneH) min 1.2) / 1.2))";
			w = "20 * 			(		((safezoneW / safezoneH) min 1.2) / 32)";
			h = "18 * 			(		(		((safezoneW / safezoneH) min 1.2) / 1.2) / 20)";
		};
		
		class BcgCommonLeft1 : RscBackgroundGUILeft {
			idc = 112001;
			backgroundType = 1;
			x = "11 * 			(		((safezoneW / safezoneH) min 1.2) / 32) + 			(safezoneX)";
			y = "1 * 			(		(		((safezoneW / safezoneH) min 1.2) / 1.2) / 20) + 			(safezoneY + safezoneH - 		(		((safezoneW / safezoneH) min 1.2) / 1.2))";
			w = "20 * 			(		((safezoneW / safezoneH) min 1.2) / 32)";
			h = "18 * 			(		(		((safezoneW / safezoneH) min 1.2) / 1.2) / 20)";
		};
		
		class BcgCommonRight1 : RscBackgroundGUIRight {
			idc = 112011;
			backgroundType = 1;
			x = "11 * 			(		((safezoneW / safezoneH) min 1.2) / 32) + 			(safezoneX)";
			y = "1 * 			(		(		((safezoneW / safezoneH) min 1.2) / 1.2) / 20) + 			(safezoneY + safezoneH - 		(		((safezoneW / safezoneH) min 1.2) / 1.2))";
			w = "20 * 			(		((safezoneW / safezoneH) min 1.2) / 32)";
			h = "18 * 			(		(		((safezoneW / safezoneH) min 1.2) / 1.2) / 20)";
		};
		
		class BcgCommonBottom1 : RscBackgroundGUIBottom {
			idc = 110011;
			backgroundType = 1;
			x = "11 * 			(		((safezoneW / safezoneH) min 1.2) / 32) + 			(safezoneX)";
			y = "1 * 			(		(		((safezoneW / safezoneH) min 1.2) / 1.2) / 20) + 			(safezoneY + safezoneH - 		(		((safezoneW / safezoneH) min 1.2) / 1.2)) +  			18 * 			(		(		((safezoneW / safezoneH) min 1.2) / 1.2) / 20) - (1 * 			(		(		((safezoneW / safezoneH) min 1.2) / 1.2) / 20))";
			w = "20 * 			(		((safezoneW / safezoneH) min 1.2) / 32)";
			h = "1 * 			(		(		((safezoneW / safezoneH) min 1.2) / 1.2) / 20)";
		};
		
		class BcgCommonTop1 : RscBackgroundGUITop {
			idc = 110021;
			backgroundType = 1;
			x = "11 * 			(		((safezoneW / safezoneH) min 1.2) / 32) + 			(safezoneX)";
			y = "1 * 			(		(		((safezoneW / safezoneH) min 1.2) / 1.2) / 20) + 			(safezoneY + safezoneH - 		(		((safezoneW / safezoneH) min 1.2) / 1.2))";
			w = "20 * 			(		((safezoneW / safezoneH) min 1.2) / 32)";
			h = "1 * 			(		(		((safezoneW / safezoneH) min 1.2) / 1.2) / 20)";
		};
	};
	
	class objects {
		class Head : RscObject {
			model = "\A3\ui_f\objects\face_preview";
			modelWoman = "\A3\ui_f\objects\face_preview";
			idc = IDC_NEW_USER_HEAD;
			type = 80;
			x = 0.75;
			y = 0.48;
			z = 0.25;
			xBack = 0.4;
			yBack = 0.25;
			zBack = 0.3;
			scale = 0.21;
			direction[] = {0, 0, 1};
			up[] = {0, 1, 0};
			faceType = "Man_A3";
			selectionLBrow = "lBrow";
			selectionMBrow = "mBrow";
			selectionRBrow = "rBrow";
			selectionLMouth = "lMouth";
			selectionMMouth = "mMouth";
			selectionRMouth = "rMouth";
			selectionEyelid = "eyelids";
			selectionLip = "LLip";
			boneHead = "head";
			boneLEye = "l_eye";
			boneREye = "r_eye";
			boneLEyelidUp = "eye_upl";
			boneREyelidUp = "eye_upr";
			boneLEyelidDown = "eye_lwl";
			boneREyelidDown = "eye_lwr";
			boneLPupil = "l_pupila";
			boneRPupil = "r_pupila";
			selectionPersonality = "personality";
			selectionGlasses = "eyelids";
		};
	};
	
	class controls {
		class B_OK {};
		class B_Cancel {};
		class TextName {};
		class ValueName {};
		class ValueId {};
		class TextFace {};
		class ValueFace {};
		class TextGlasses {};
		class ValueGlasses {};
		class TextSpeaker {};
		class ValueSpeaker {};
		class TextPitch {};
		class ValuePitch {};
		class TextSquad {};
		class ValueSquad {};
		class Title {};
		
		class CA_Title2 : CA_Title {
			idc = 1000;
			text = $STR_CA_NEWUSER_TITLE2;
			x = "1 * 			(		((safezoneW / safezoneH) min 1.2) / 32) + 			(safezoneX)";
			y = "1 * 			(		(		((safezoneW / safezoneH) min 1.2) / 1.2) / 20) + 			(safezoneY + safezoneH - 		(		((safezoneW / safezoneH) min 1.2) / 1.2))";
			w = "10 * 			(		((safezoneW / safezoneH) min 1.2) / 32)";
			h = "1 * 			(		(		((safezoneW / safezoneH) min 1.2) / 1.2) / 20)";
		};
		
		class CA_ButtonContinue : RscShortcutButton {
			idc = 1;
			default = 1;
			text = $STR_DISP_OK;
			x = "21 * 			(		((safezoneW / safezoneH) min 1.2) / 32) + 			(safezoneX)";
			y = "18 * 			(		(		((safezoneW / safezoneH) min 1.2) / 1.2) / 20) + 			(safezoneY + safezoneH - 		(		((safezoneW / safezoneH) min 1.2) / 1.2))";
			w = "10 * 			(		((safezoneW / safezoneH) min 1.2) / 32)";
			h = "1 * 			(		(		((safezoneW / safezoneH) min 1.2) / 1.2) / 20)";
		};
		
		class CA_ButtonCancel : RscShortcutButton {
			idc = 2;
			default = 0;
			text = $STR_CA_CANCEL;
			x = "1 * 			(		((safezoneW / safezoneH) min 1.2) / 32) + 			(safezoneX)";
			y = "18 * 			(		(		((safezoneW / safezoneH) min 1.2) / 1.2) / 20) + 			(safezoneY + safezoneH - 		(		((safezoneW / safezoneH) min 1.2) / 1.2))";
			w = "10 * 			(		((safezoneW / safezoneH) min 1.2) / 32)";
			h = "1 * 			(		(		((safezoneW / safezoneH) min 1.2) / 1.2) / 20)";
		};
		
		class CA_TextPlayer2 : RscText {
			idc = 1001;
			text = $STR_DISP_NEW_USER_NAME;
			x = "1.5 * 			(		((safezoneW / safezoneH) min 1.2) / 32) + 			(safezoneX)";
			y = "2.5 * 			(		(		((safezoneW / safezoneH) min 1.2) / 1.2) / 20) + 			(safezoneY + safezoneH - 		(		((safezoneW / safezoneH) min 1.2) / 1.2))";
			w = "9 * 			(		((safezoneW / safezoneH) min 1.2) / 32)";
			h = "1 * 			(		(		((safezoneW / safezoneH) min 1.2) / 1.2) / 20)";
		};
		
		class CA_NameValue : RscEdit {
			idc = IDC_NEW_USER_NAME;
			x = "1.5 * 			(		((safezoneW / safezoneH) min 1.2) / 32) + 			(safezoneX)";
			y = "3.5 * 			(		(		((safezoneW / safezoneH) min 1.2) / 1.2) / 20) + 			(safezoneY + safezoneH - 		(		((safezoneW / safezoneH) min 1.2) / 1.2))";
			w = "9 * 			(		((safezoneW / safezoneH) min 1.2) / 32)";
			h = "1 * 			(		(		((safezoneW / safezoneH) min 1.2) / 1.2) / 20)";
		};
		
		class CA_FaceText : RscText {
			idc = 1002;
			text = $STR_DISP_NEW_USER_FACE;
			x = "1.5 * 			(		((safezoneW / safezoneH) min 1.2) / 32) + 			(safezoneX)";
			y = "4.5 * 			(		(		((safezoneW / safezoneH) min 1.2) / 1.2) / 20) + 			(safezoneY + safezoneH - 		(		((safezoneW / safezoneH) min 1.2) / 1.2))";
			w = "9 * 			(		((safezoneW / safezoneH) min 1.2) / 32)";
			h = "1 * 			(		(		((safezoneW / safezoneH) min 1.2) / 1.2) / 20)";
		};
		
		class CA_FaceValue : RscCombo {
			idc = IDC_NEW_USER_FACE;
			rows = 3;
			x = "1.5 * 			(		((safezoneW / safezoneH) min 1.2) / 32) + 			(safezoneX)";
			y = "5.5 * 			(		(		((safezoneW / safezoneH) min 1.2) / 1.2) / 20) + 			(safezoneY + safezoneH - 		(		((safezoneW / safezoneH) min 1.2) / 1.2))";
			w = "9 * 			(		((safezoneW / safezoneH) min 1.2) / 32)";
			h = "1 * 			(		(		((safezoneW / safezoneH) min 1.2) / 1.2) / 20)";
		};
		
		class CA_GlassText : CA_FaceText {
			idc = 1003;
			text = $STR_DISP_NEW_USER_GLASSES;
			x = "1.5 * 			(		((safezoneW / safezoneH) min 1.2) / 32) + 			(safezoneX)";
			y = "6.5 * 			(		(		((safezoneW / safezoneH) min 1.2) / 1.2) / 20) + 			(safezoneY + safezoneH - 		(		((safezoneW / safezoneH) min 1.2) / 1.2))";
			w = "9 * 			(		((safezoneW / safezoneH) min 1.2) / 32)";
			h = "1 * 			(		(		((safezoneW / safezoneH) min 1.2) / 1.2) / 20)";
		};
		
		class CA_ValueGlasses2 : RscCombo {
			idc = IDC_NEW_USER_GLASSES;
			x = "1.5 * 			(		((safezoneW / safezoneH) min 1.2) / 32) + 			(safezoneX)";
			y = "7.5 * 			(		(		((safezoneW / safezoneH) min 1.2) / 1.2) / 20) + 			(safezoneY + safezoneH - 		(		((safezoneW / safezoneH) min 1.2) / 1.2))";
			w = "9 * 			(		((safezoneW / safezoneH) min 1.2) / 32)";
			h = "1 * 			(		(		((safezoneW / safezoneH) min 1.2) / 1.2) / 20)";
		};
		
		class CA_SpeakerText : CA_FaceText {
			idc = 1004;
			text = $STR_DISP_NEW_USER_SPEAKER;
			x = "1.5 * 			(		((safezoneW / safezoneH) min 1.2) / 32) + 			(safezoneX)";
			y = "8.5 * 			(		(		((safezoneW / safezoneH) min 1.2) / 1.2) / 20) + 			(safezoneY + safezoneH - 		(		((safezoneW / safezoneH) min 1.2) / 1.2))";
			w = "9 * 			(		((safezoneW / safezoneH) min 1.2) / 32)";
			h = "1 * 			(		(		((safezoneW / safezoneH) min 1.2) / 1.2) / 20)";
		};
		
		class CA_ValueSpeaker2 : RscCombo {
			idc = IDC_NEW_USER_SPEAKER;
			x = "1.5 * 			(		((safezoneW / safezoneH) min 1.2) / 32) + 			(safezoneX)";
			y = "9.5 * 			(		(		((safezoneW / safezoneH) min 1.2) / 1.2) / 20) + 			(safezoneY + safezoneH - 		(		((safezoneW / safezoneH) min 1.2) / 1.2))";
			w = "9 * 			(		((safezoneW / safezoneH) min 1.2) / 32)";
			h = "1 * 			(		(		((safezoneW / safezoneH) min 1.2) / 1.2) / 20)";
		};
		
		class CA_TextPitch2 : CA_FaceText {
			idc = 1005;
			text = $STR_DISP_NEW_USER_PITCH;
			x = "1.5 * 			(		((safezoneW / safezoneH) min 1.2) / 32) + 			(safezoneX)";
			y = "10.5 * 			(		(		((safezoneW / safezoneH) min 1.2) / 1.2) / 20) + 			(safezoneY + safezoneH - 		(		((safezoneW / safezoneH) min 1.2) / 1.2))";
			w = "9 * 			(		((safezoneW / safezoneH) min 1.2) / 32)";
			h = "1 * 			(		(		((safezoneW / safezoneH) min 1.2) / 1.2) / 20)";
		};
		
		class CA_ValuePitch2 : RscXSliderH {
			idc = IDC_NEW_USER_PITCH;
			x = "1.5 * 			(		((safezoneW / safezoneH) min 1.2) / 32) + 			(safezoneX)";
			y = "11.5 * 			(		(		((safezoneW / safezoneH) min 1.2) / 1.2) / 20) + 			(safezoneY + safezoneH - 		(		((safezoneW / safezoneH) min 1.2) / 1.2))";
			w = "9 * 			(		((safezoneW / safezoneH) min 1.2) / 32)";
			h = "1 * 			(		(		((safezoneW / safezoneH) min 1.2) / 1.2) / 20)";
		};
		
		class CA_SquadText : CA_FaceText {
			idc = IDC_NEW_USER_SQUAD_TEXT;
			text = $STR_DISP_NEW_USER_SQUAD;
			x = "1.5 * 			(		((safezoneW / safezoneH) min 1.2) / 32) + 			(safezoneX)";
			y = "12.5 * 			(		(		((safezoneW / safezoneH) min 1.2) / 1.2) / 20) + 			(safezoneY + safezoneH - 		(		((safezoneW / safezoneH) min 1.2) / 1.2))";
			w = "9 * 			(		((safezoneW / safezoneH) min 1.2) / 32)";
			h = "1 * 			(		(		((safezoneW / safezoneH) min 1.2) / 1.2) / 20)";
		};
		
		class CA_SquadValue : CA_NameValue {
			idc = IDC_NEW_USER_SQUAD;
			x = "1.5 * 			(		((safezoneW / safezoneH) min 1.2) / 32) + 			(safezoneX)";
			y = "13.5 * 			(		(		((safezoneW / safezoneH) min 1.2) / 1.2) / 20) + 			(safezoneY + safezoneH - 		(		((safezoneW / safezoneH) min 1.2) / 1.2))";
			w = "9 * 			(		((safezoneW / safezoneH) min 1.2) / 32)";
			h = "1 * 			(		(		((safezoneW / safezoneH) min 1.2) / 1.2) / 20)";
		};
		
		class CA_ValueID : CA_SquadText {
			idc = IDC_NEW_USER_ID;
			x = "11 * 			(		((safezoneW / safezoneH) min 1.2) / 32) + 			(safezoneX)";
			y = "1 * 			(		(		((safezoneW / safezoneH) min 1.2) / 1.2) / 20) + 			(safezoneY + safezoneH - 		(		((safezoneW / safezoneH) min 1.2) / 1.2))";
			w = "20 * 			(		((safezoneW / safezoneH) min 1.2) / 32)";
			h = "1 * 			(		(		((safezoneW / safezoneH) min 1.2) / 1.2) / 20)";
		};
	};
};
