// config.bin - 14:14:50 09/06/14, generated in 0.00 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Disabled, Automatic comments: Enabled

enum {
	DESTRUCTENGINE = 2,
	DESTRUCTDEFAULT = 6,
	DESTRUCTWRECK = 7,
	DESTRUCTTREE = 3,
	DESTRUCTTENT = 4,
	DESTRUCTNO = 0,
	DESTRUCTMAN = 5,
	DESTRUCTBUILDING = 1,
};

class CfgPatches {
	class CAStructures_PMC {
		units[] = {};
		weapons[] = {};
		requiredVersion = 1.54;
		requiredAddons[] = {};
	};
};
