// Generated by unRap v1.06 by Kegetys

class RscDisplayClientWait : RscDisplayMPPlayers {
	class LoadingPic : RscPicture {
		x = 0;
		y = 0;
		w = 1;
		h = 1;
		text = "#(argb,8,8,3)color(0,0,0,0)";
		colortext[] = {1, 1, 1, 1};
	};
	
	class Cancel : CA_Ok {
		default = 1;
		idc = 2;
		y = 0.85;
		onMouseEnter = "disableSerialization; _display = ctrlParent (_this select 0); _ctrl031 = _display displayCtrl 031; _ctrl032 = _display displayCtrl 032; _ctrl031 ctrlSetTextColor [0.84,1,0.55,1]; _ctrl032 ctrlSetTextColor [0, 0, 0, 1]";
		onMouseExit = "disableSerialization; _display = ctrlParent (_this select 0); _ctrl031 = _display displayCtrl 031; _ctrl032 = _display displayCtrl 032; _ctrl031 ctrlSetTextColor [1,1,1,0.9]; _ctrl032 ctrlSetTextColor [0, 0, 0, 0.9]";
		onSetFocus = "disableSerialization; _display = ctrlParent (_this select 0); _ctrl031 = _display displayCtrl 031; _ctrl032 = _display displayCtrl 032; _ctrl031 ctrlSetTextColor [0.84,1,0.55,1]; _ctrl032 ctrlSetTextColor [0, 0, 0, 1]";
		onKillFocus = "disableSerialization; _display = ctrlParent (_this select 0); _ctrl031 = _display displayCtrl 031; _ctrl032 = _display displayCtrl 032; _ctrl031 ctrlSetTextColor [1,1,1,0.9]; _ctrl032 ctrlSetTextColor [0, 0, 0, 0.9]";
	};
	
	class Cancel_image : CA_Ok_image {
		idc = 31;
		y = 0.85;
	};
	
	class Cancel_image2 : CA_Ok_image2 {
		y = 0.85;
	};
	
	class Cancel_text : CA_Ok_text {
		idc = 32;
		y = 0.85;
		text = $STR_CA_CANCEL;
	};
};
