// Generated by unRap v1.06 by Kegetys

class RscDisplayServer : RscDisplayRemoteMissions {
	colorEditor[] = {0.196, 0.592, 0.706, 1};
	colorWizard[] = {0.863, 0.584, 0.0, 1};
	colorMission[] = {1, 1, 1, 1.0};
	colorMissionEditor[] = {0.196, 0.592, 0.706, 1};
	colorMissionWizard[] = {0.863, 0.584, 0.0, 1};
	colorMissionSteam[] = {0.863, 0.584, 0.0, 1};
	class ControlsBackground {};
	class controls {};
};
