// Generated by unRap v1.06 by Kegetys

class RscDisplayOptionsLayout {
	idd = 154;
	enableSimulation = 0;
	onLoad = "[""onLoad"",_this,""RscDisplayOptionsLayout"",'GUI'] call compile preprocessfilelinenumbers ""A3\ui_f\scripts\initDisplay.sqf""";
	onUnload = "[""onUnload"",_this,""RscDisplayOptionsLayout"",'GUI'] call compile preprocessfilelinenumbers ""A3\ui_f\scripts\initDisplay.sqf""";
	
	class controlsBackground {
		class Element000 : RscActiveText {
			idc = 12000;
			style = 48;
			shadow = false;
			x = 0;
			y = 0;
			w = 0;
			h = 0;
			color[] = {1, 1, 1, 1};
			colorActive[] = {"(profilenamespace getvariable ['GUI_BCG_RGB_R',0.69])", "(profilenamespace getvariable ['GUI_BCG_RGB_G',0.75])", "(profilenamespace getvariable ['GUI_BCG_RGB_B',0.5])", 1};
		};
		
		class Element001 : RscActiveText {
			idc = 12001;
			style = 48;
			shadow = false;
			x = 0;
			y = 0;
			w = 0;
			h = 0;
			color[] = {1, 1, 1, 1};
			colorActive[] = {"(profilenamespace getvariable ['GUI_BCG_RGB_R',0.69])", "(profilenamespace getvariable ['GUI_BCG_RGB_G',0.75])", "(profilenamespace getvariable ['GUI_BCG_RGB_B',0.5])", 1};
		};
		
		class Element002 : RscActiveText {
			idc = 12002;
			style = 48;
			shadow = false;
			x = 0;
			y = 0;
			w = 0;
			h = 0;
			color[] = {1, 1, 1, 1};
			colorActive[] = {"(profilenamespace getvariable ['GUI_BCG_RGB_R',0.69])", "(profilenamespace getvariable ['GUI_BCG_RGB_G',0.75])", "(profilenamespace getvariable ['GUI_BCG_RGB_B',0.5])", 1};
		};
		
		class Element003 : RscActiveText {
			idc = 12003;
			style = 48;
			shadow = false;
			x = 0;
			y = 0;
			w = 0;
			h = 0;
			color[] = {1, 1, 1, 1};
			colorActive[] = {"(profilenamespace getvariable ['GUI_BCG_RGB_R',0.69])", "(profilenamespace getvariable ['GUI_BCG_RGB_G',0.75])", "(profilenamespace getvariable ['GUI_BCG_RGB_B',0.5])", 1};
		};
		
		class Element004 : RscActiveText {
			idc = 12004;
			style = 48;
			shadow = false;
			x = 0;
			y = 0;
			w = 0;
			h = 0;
			color[] = {1, 1, 1, 1};
			colorActive[] = {"(profilenamespace getvariable ['GUI_BCG_RGB_R',0.69])", "(profilenamespace getvariable ['GUI_BCG_RGB_G',0.75])", "(profilenamespace getvariable ['GUI_BCG_RGB_B',0.5])", 1};
		};
		
		class Element005 : RscActiveText {
			idc = 12005;
			style = 48;
			shadow = false;
			x = 0;
			y = 0;
			w = 0;
			h = 0;
			color[] = {1, 1, 1, 1};
			colorActive[] = {"(profilenamespace getvariable ['GUI_BCG_RGB_R',0.69])", "(profilenamespace getvariable ['GUI_BCG_RGB_G',0.75])", "(profilenamespace getvariable ['GUI_BCG_RGB_B',0.5])", 1};
		};
		
		class Element006 : RscActiveText {
			idc = 12006;
			style = 48;
			shadow = false;
			x = 0;
			y = 0;
			w = 0;
			h = 0;
			color[] = {1, 1, 1, 1};
			colorActive[] = {"(profilenamespace getvariable ['GUI_BCG_RGB_R',0.69])", "(profilenamespace getvariable ['GUI_BCG_RGB_G',0.75])", "(profilenamespace getvariable ['GUI_BCG_RGB_B',0.5])", 1};
		};
		
		class Element007 : RscActiveText {
			idc = 12007;
			style = 48;
			shadow = false;
			x = 0;
			y = 0;
			w = 0;
			h = 0;
			color[] = {1, 1, 1, 1};
			colorActive[] = {"(profilenamespace getvariable ['GUI_BCG_RGB_R',0.69])", "(profilenamespace getvariable ['GUI_BCG_RGB_G',0.75])", "(profilenamespace getvariable ['GUI_BCG_RGB_B',0.5])", 1};
		};
		
		class Element008 : RscActiveText {
			idc = 12008;
			style = 48;
			shadow = false;
			x = 0;
			y = 0;
			w = 0;
			h = 0;
			color[] = {1, 1, 1, 1};
			colorActive[] = {"(profilenamespace getvariable ['GUI_BCG_RGB_R',0.69])", "(profilenamespace getvariable ['GUI_BCG_RGB_G',0.75])", "(profilenamespace getvariable ['GUI_BCG_RGB_B',0.5])", 1};
		};
		
		class Element009 : RscActiveText {
			idc = 12009;
			style = 48;
			shadow = false;
			x = 0;
			y = 0;
			w = 0;
			h = 0;
			color[] = {1, 1, 1, 1};
			colorActive[] = {"(profilenamespace getvariable ['GUI_BCG_RGB_R',0.69])", "(profilenamespace getvariable ['GUI_BCG_RGB_G',0.75])", "(profilenamespace getvariable ['GUI_BCG_RGB_B',0.5])", 1};
		};
		
		class Element010 : RscActiveText {
			idc = 12010;
			style = 48;
			shadow = false;
			x = 0;
			y = 0;
			w = 0;
			h = 0;
			color[] = {1, 1, 1, 1};
			colorActive[] = {"(profilenamespace getvariable ['GUI_BCG_RGB_R',0.69])", "(profilenamespace getvariable ['GUI_BCG_RGB_G',0.75])", "(profilenamespace getvariable ['GUI_BCG_RGB_B',0.5])", 1};
		};
		
		class Element011 : RscActiveText {
			idc = 12011;
			style = 48;
			shadow = false;
			x = 0;
			y = 0;
			w = 0;
			h = 0;
			color[] = {1, 1, 1, 1};
			colorActive[] = {"(profilenamespace getvariable ['GUI_BCG_RGB_R',0.69])", "(profilenamespace getvariable ['GUI_BCG_RGB_G',0.75])", "(profilenamespace getvariable ['GUI_BCG_RGB_B',0.5])", 1};
		};
		
		class Element012 : RscActiveText {
			idc = 12012;
			style = 48;
			shadow = false;
			x = 0;
			y = 0;
			w = 0;
			h = 0;
			color[] = {1, 1, 1, 1};
			colorActive[] = {"(profilenamespace getvariable ['GUI_BCG_RGB_R',0.69])", "(profilenamespace getvariable ['GUI_BCG_RGB_G',0.75])", "(profilenamespace getvariable ['GUI_BCG_RGB_B',0.5])", 1};
		};
		
		class Element013 : RscActiveText {
			idc = 12013;
			style = 48;
			shadow = false;
			x = 0;
			y = 0;
			w = 0;
			h = 0;
			color[] = {1, 1, 1, 1};
			colorActive[] = {"(profilenamespace getvariable ['GUI_BCG_RGB_R',0.69])", "(profilenamespace getvariable ['GUI_BCG_RGB_G',0.75])", "(profilenamespace getvariable ['GUI_BCG_RGB_B',0.5])", 1};
		};
		
		class Element014 : RscActiveText {
			idc = 12014;
			style = 48;
			shadow = false;
			x = 0;
			y = 0;
			w = 0;
			h = 0;
			color[] = {1, 1, 1, 1};
			colorActive[] = {"(profilenamespace getvariable ['GUI_BCG_RGB_R',0.69])", "(profilenamespace getvariable ['GUI_BCG_RGB_G',0.75])", "(profilenamespace getvariable ['GUI_BCG_RGB_B',0.5])", 1};
		};
		
		class Element015 : RscActiveText {
			idc = 12015;
			style = 48;
			shadow = false;
			x = 0;
			y = 0;
			w = 0;
			h = 0;
			color[] = {1, 1, 1, 1};
			colorActive[] = {"(profilenamespace getvariable ['GUI_BCG_RGB_R',0.69])", "(profilenamespace getvariable ['GUI_BCG_RGB_G',0.75])", "(profilenamespace getvariable ['GUI_BCG_RGB_B',0.5])", 1};
		};
		
		class Element016 : RscActiveText {
			idc = 12016;
			style = 48;
			shadow = false;
			x = 0;
			y = 0;
			w = 0;
			h = 0;
			color[] = {1, 1, 1, 1};
			colorActive[] = {"(profilenamespace getvariable ['GUI_BCG_RGB_R',0.69])", "(profilenamespace getvariable ['GUI_BCG_RGB_G',0.75])", "(profilenamespace getvariable ['GUI_BCG_RGB_B',0.5])", 1};
		};
		
		class Element017 : RscActiveText {
			idc = 12017;
			style = 48;
			shadow = false;
			x = 0;
			y = 0;
			w = 0;
			h = 0;
			color[] = {1, 1, 1, 1};
			colorActive[] = {"(profilenamespace getvariable ['GUI_BCG_RGB_R',0.69])", "(profilenamespace getvariable ['GUI_BCG_RGB_G',0.75])", "(profilenamespace getvariable ['GUI_BCG_RGB_B',0.5])", 1};
		};
		
		class Element018 : RscActiveText {
			idc = 12018;
			style = 48;
			shadow = false;
			x = 0;
			y = 0;
			w = 0;
			h = 0;
			color[] = {1, 1, 1, 1};
			colorActive[] = {"(profilenamespace getvariable ['GUI_BCG_RGB_R',0.69])", "(profilenamespace getvariable ['GUI_BCG_RGB_G',0.75])", "(profilenamespace getvariable ['GUI_BCG_RGB_B',0.5])", 1};
		};
	};
	
	class controls {
		class CenterW : RscText {
			x = "safezoneXAbs";
			y = 0.5;
			w = "safezoneWAbs";
			h = 0.002;
			idc = 1005;
			colorBackground[] = {0, 1, 1, 1};
		};
		
		class CenterH : RscText {
			x = 0.5;
			y = "safezoneY";
			w = 0.002*(3/4);
			h = "safezoneH";
			idc = 1006;
			colorBackground[] = {0, 1, 1, 1};
		};
		
		class Tooltip : RscStructuredText {
			x = 0;
			y = 0;
			idc = 1100;
			w = "8 * 					(			((safezoneW / safezoneH) min 1.2) / 40)";
			h = "1 * 					(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
			colorBackground[] = {0, 0, 0, 1};
		};
		
		class Title : RscText {
			colorBackground[] = {"(profilenamespace getvariable ['GUI_BCG_RGB_R',0.69])", "(profilenamespace getvariable ['GUI_BCG_RGB_G',0.75])", "(profilenamespace getvariable ['GUI_BCG_RGB_B',0.5])", "(profilenamespace getvariable ['GUI_BCG_RGB_A',0.8])"};
			idc = 1000;
			text = "$STR_A3_RscDisplayOptionsLayout_Title";
			x = "11 * 					(			((safezoneW / safezoneH) min 1.2) / 40) + 		(safezoneX + (safezoneW - 					((safezoneW / safezoneH) min 1.2))/2)";
			y = "8.9 * 					(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25) + 		(safezoneY + (safezoneH - 					(			((safezoneW / safezoneH) min 1.2) / 1.2))/2)";
			w = "18 * 					(			((safezoneW / safezoneH) min 1.2) / 40)";
			h = "1 * 					(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
		};
		
		class Background : RscText {
			colorBackground[] = {0, 0, 0, 0.7};
			idc = 1001;
			x = "11 * 					(			((safezoneW / safezoneH) min 1.2) / 40) + 		(safezoneX + (safezoneW - 					((safezoneW / safezoneH) min 1.2))/2)";
			y = "10 * 					(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25) + 		(safezoneY + (safezoneH - 					(			((safezoneW / safezoneH) min 1.2) / 1.2))/2)";
			w = "18 * 					(			((safezoneW / safezoneH) min 1.2) / 40)";
			h = "5 * 					(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
		};
		
		class TagsText : RscText {
			idc = 1002;
			text = "$STR_A3_RscDisplayOptionsLayout_TagsText";
			x = "11.5 * 					(			((safezoneW / safezoneH) min 1.2) / 40) + 		(safezoneX + (safezoneW - 					((safezoneW / safezoneH) min 1.2))/2)";
			y = "10 * 					(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25) + 		(safezoneY + (safezoneH - 					(			((safezoneW / safezoneH) min 1.2) / 1.2))/2)";
			w = "17 * 					(			((safezoneW / safezoneH) min 1.2) / 40)";
			h = "1 * 					(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
		};
		
		class Tags : RscCombo {
			idc = 2100;
			x = "11.5 * 					(			((safezoneW / safezoneH) min 1.2) / 40) + 		(safezoneX + (safezoneW - 					((safezoneW / safezoneH) min 1.2))/2)";
			y = "11 * 					(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25) + 		(safezoneY + (safezoneH - 					(			((safezoneW / safezoneH) min 1.2) / 1.2))/2)";
			w = "17 * 					(			((safezoneW / safezoneH) min 1.2) / 40)";
			h = "1 * 					(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
		};
		
		class PresetsLabel : RscText {
			idc = 1003;
			text = "$STR_A3_RscDisplayOptionsLayout_PresetsLabel";
			x = "11.5 * 					(			((safezoneW / safezoneH) min 1.2) / 40) + 		(safezoneX + (safezoneW - 					((safezoneW / safezoneH) min 1.2))/2)";
			y = "12 * 					(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25) + 		(safezoneY + (safezoneH - 					(			((safezoneW / safezoneH) min 1.2) / 1.2))/2)";
			w = "17 * 					(			((safezoneW / safezoneH) min 1.2) / 40)";
			h = "1 * 					(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
		};
		
		class Presets : RscCombo {
			idc = 2101;
			x = "11.5 * 					(			((safezoneW / safezoneH) min 1.2) / 40) + 		(safezoneX + (safezoneW - 					((safezoneW / safezoneH) min 1.2))/2)";
			y = "13 * 					(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25) + 		(safezoneY + (safezoneH - 					(			((safezoneW / safezoneH) min 1.2) / 1.2))/2)";
			w = "17 * 					(			((safezoneW / safezoneH) min 1.2) / 40)";
			h = "1 * 					(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
		};
		
		class ButtonCancel : RscButtonMenuCancel {
			x = "11 * 					(			((safezoneW / safezoneH) min 1.2) / 40) + 		(safezoneX + (safezoneW - 					((safezoneW / safezoneH) min 1.2))/2)";
			y = "15.1 * 					(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25) + 		(safezoneY + (safezoneH - 					(			((safezoneW / safezoneH) min 1.2) / 1.2))/2)";
			w = "5.9 * 					(			((safezoneW / safezoneH) min 1.2) / 40)";
			h = "1 * 					(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
		};
		
		class ButtonOK : RscButtonMenuOK {
			x = "23.1 * 					(			((safezoneW / safezoneH) min 1.2) / 40) + 		(safezoneX + (safezoneW - 					((safezoneW / safezoneH) min 1.2))/2)";
			y = "15.1 * 					(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25) + 		(safezoneY + (safezoneH - 					(			((safezoneW / safezoneH) min 1.2) / 1.2))/2)";
			w = "5.9 * 					(			((safezoneW / safezoneH) min 1.2) / 40)";
			h = "1 * 					(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
		};
		
		class ButtonSave : RscButtonMenu {
			idc = 2400;
			text = "$STR_A3_RscDisplayOptionsLayout_ButtonSave";
			x = "17 * 					(			((safezoneW / safezoneH) min 1.2) / 40) + 		(safezoneX + (safezoneW - 					((safezoneW / safezoneH) min 1.2))/2)";
			y = "15.1 * 					(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25) + 		(safezoneY + (safezoneH - 					(			((safezoneW / safezoneH) min 1.2) / 1.2))/2)";
			w = "6 * 					(			((safezoneW / safezoneH) min 1.2) / 40)";
			h = "1 * 					(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
		};
	};
};
