// Generated by unRap v1.06 by Kegetys

class CfgChainOfCommand {
	class Sides {
		class West {
			name = $STR_WEST;
			prefix = "b_";
			color[] = {"(profilenamespace getvariable ['Map_BLUFOR_R',0])", "(profilenamespace getvariable ['Map_BLUFOR_G',1])", "(profilenamespace getvariable ['Map_BLUFOR_B',1])", "(profilenamespace getvariable ['Map_BLUFOR_A',0.8])"};
			size = 1;
		};
		
		class East {
			name = $STR_EAST;
			prefix = "o_";
			color[] = {"(profilenamespace getvariable ['Map_OPFOR_R',0])", "(profilenamespace getvariable ['Map_OPFOR_G',1])", "(profilenamespace getvariable ['Map_OPFOR_B',1])", "(profilenamespace getvariable ['Map_OPFOR_A',0.8])"};
			size = 0.65;
		};
		
		class Resistance {
			name = "$STR_Guerrila";
			prefix = "n_";
			color[] = {"(profilenamespace getvariable ['Map_Independent_R',0])", "(profilenamespace getvariable ['Map_Independent_G',1])", "(profilenamespace getvariable ['Map_Independent_B',1])", "(profilenamespace getvariable ['Map_Independent_A',0.8])"};
			size = 0.75;
		};
		
		class Civilian {
			name = "$STR_Civilian";
			prefix = "n_";
			color[] = {"(profilenamespace getvariable ['Map_Civilian_R',0])", "(profilenamespace getvariable ['Map_Civilian_G',1])", "(profilenamespace getvariable ['Map_Civilian_B',1])", "(profilenamespace getvariable ['Map_Civilian_A',0.8])"};
			size = 0.75;
		};
		
		class Unknown {
			name = "$STR_DN_Unknown";
			prefix = "n_";
			color[] = {"(profilenamespace getvariable ['Map_Unknown_R',0])", "(profilenamespace getvariable ['Map_Unknown_G',1])", "(profilenamespace getvariable ['Map_Unknown_B',1])", "(profilenamespace getvariable ['Map_Unknown_A',0.8])"};
			size = 0.75;
		};
	};
	
	class Sizes {
		class Size1 {
			size = 1;
		};
		
		class Size2 {
			size = 2;
		};
		
		class Size3 {
			size = 3;
		};
		
		class Size4 {
			size = 4;
		};
		
		class Size5 {
			size = 5;
		};
		
		class Size6 {
			size = 6;
		};
		
		class Size7 {
			size = 7;
		};
		
		class Size8 {
			size = 8;
		};
		
		class Size9 {
			size = 9;
		};
		
		class Size10 {
			size = 10;
		};
		
		class Size11 {
			size = 11;
		};
		
		class FireTeam {
			size = 0;
			name = "$STR_A3_CfgChainOfCommand_Sizes_FireTeam_name";
			nameShort = "$STR_A3_CfgChainOfCommand_Sizes_FireTeam_nameShort";
			nameGender = "$STR_A3_CfgChainOfCommand_Sizes_FireTeam_nameGender";
			commanderRank = "Corporal";
			texture = "group_0";
			textDefault = "$STR_A3_CfgChainOfCommand_Sizes_FireTeam_textDefault";
			textShortDefault = "$STR_A3_CfgChainOfCommand_Sizes_FireTeam_textShortDefault";
		};
		
		class Squad {
			size = 1;
			name = "$STR_A3_CfgChainOfCommand_Sizes_Squad_name";
			nameShort = "$STR_A3_CfgChainOfCommand_Sizes_Squad_nameShort";
			nameGender = "$STR_A3_CfgChainOfCommand_Sizes_Squad_nameGender";
			commanderRank = "Sergeant";
			texture = "group_1";
			textDefault = "$STR_A3_CfgChainOfCommand_Sizes_Squad_textDefault";
			textShortDefault = "$STR_A3_CfgChainOfCommand_Sizes_Squad_textShortDefault";
		};
		
		class Section {
			size = 2;
			name = "$STR_A3_CfgChainOfCommand_Sizes_Section_name";
			nameShort = "$STR_A3_CfgChainOfCommand_Sizes_Section_nameShort";
			nameGender = "$STR_A3_CfgChainOfCommand_Sizes_Section_nameGender";
			commanderRank = "";
			texture = "group_2";
			textDefault = "$STR_A3_CfgChainOfCommand_Sizes_Section_textDefault";
			textShortDefault = "$STR_A3_CfgChainOfCommand_Sizes_Section_textShortDefault";
		};
		
		class Platoon {
			size = 3;
			name = "$STR_A3_CfgChainOfCommand_Sizes_Platoon_name";
			nameShort = "$STR_A3_CfgChainOfCommand_Sizes_Platoon_nameShort";
			nameGender = "$STR_A3_CfgChainOfCommand_Sizes_Platoon_nameGender";
			commanderRank = "Lieutenant";
			texture = "group_3";
			textDefault = "$STR_A3_CfgChainOfCommand_Sizes_Platoon_textDefault";
			textShortDefault = "$STR_A3_CfgChainOfCommand_Sizes_Platoon_textShortDefault";
		};
		
		class Company {
			size = 4;
			name = "$STR_A3_CfgChainOfCommand_Sizes_Company_name";
			nameShort = "$STR_A3_CfgChainOfCommand_Sizes_Company_nameShort";
			nameGender = "$STR_A3_CfgChainOfCommand_Sizes_Company_nameGender";
			commanderRank = "Captain";
			texture = "group_4";
			textDefault = "$STR_A3_CfgChainOfCommand_Sizes_Company_textDefault";
			textShortDefault = "$STR_A3_CfgChainOfCommand_Sizes_Company_textShortDefault";
		};
		
		class Troop : Company {
			name = "$STR_A3_CfgChainOfCommand_Sizes_Troop_name";
			nameShort = "$STR_A3_CfgChainOfCommand_Sizes_Troop_nameShort";
			nameGender = "$STR_A3_CfgChainOfCommand_Sizes_Troop_nameGender";
			textDefault = "$STR_A3_CfgChainOfCommand_Sizes_Troop_textDefault";
			textShortDefault = "$STR_A3_CfgChainOfCommand_Sizes_Troop_textShortDefault";
		};
		
		class Battalion {
			size = 5;
			name = "$STR_A3_CfgChainOfCommand_Sizes_Battalion_name";
			nameShort = "$STR_A3_CfgChainOfCommand_Sizes_Battalion_nameShort";
			nameGender = "$STR_A3_CfgChainOfCommand_Sizes_Battalion_nameGender";
			commanderRank = "Colonel";
			texture = "group_5";
			textDefault = "$STR_A3_CfgChainOfCommand_Sizes_Battalion_textDefault";
			textShortDefault = "$STR_A3_CfgChainOfCommand_Sizes_Battalion_textShortDefault";
		};
		
		class Squadron : Battalion {
			name = "$STR_A3_CfgChainOfCommand_Sizes_Squadron_name";
			nameShort = "$STR_A3_CfgChainOfCommand_Sizes_Squadron_nameShort";
			nameGender = "$STR_A3_CfgChainOfCommand_Sizes_Squadron_nameGender";
			textDefault = "$STR_A3_CfgChainOfCommand_Sizes_Squadron_textDefault";
			textShortDefault = "$STR_A3_CfgChainOfCommand_Sizes_Squadron_textShortDefault";
		};
		
		class Regiment {
			size = 6;
			name = "$STR_A3_CfgChainOfCommand_Sizes_Regiment_name";
			nameShort = "$STR_A3_CfgChainOfCommand_Sizes_Regiment_nameShort";
			nameGender = "$STR_A3_CfgChainOfCommand_Sizes_Regiment_nameGender";
			commanderRank = "Colonel";
			texture = "group_6";
			textDefault = "$STR_A3_CfgChainOfCommand_Sizes_Regiment_textDefault";
			textShortDefault = "$STR_A3_CfgChainOfCommand_Sizes_Regiment_textShortDefault";
		};
		
		class Brigade {
			size = 7;
			name = "$STR_A3_CfgChainOfCommand_Sizes_Brigade_name";
			nameShort = "$STR_A3_CfgChainOfCommand_Sizes_Brigade_nameShort";
			nameGender = "$STR_A3_CfgChainOfCommand_Sizes_Brigade_nameGender";
			commanderRank = "General";
			texture = "group_7";
			textDefault = "$STR_A3_CfgChainOfCommand_Sizes_Brigade_textDefault";
			textShortDefault = "$STR_A3_CfgChainOfCommand_Sizes_Brigade_textShortDefault";
		};
		
		class BCT : Brigade {
			name = "$STR_A3_CfgChainOfCommand_Sizes_BCT_name";
			nameShort = "$STR_A3_CfgChainOfCommand_Sizes_BCT_nameShort";
			nameGender = "$STR_A3_CfgChainOfCommand_Sizes_BCT_nameGender";
			textDefault = "$STR_A3_CfgChainOfCommand_Sizes_BCT_textDefault";
			textShortDefault = "$STR_A3_CfgChainOfCommand_Sizes_BCT_textShortDefault";
		};
		
		class IBCT : Brigade {
			name = "$STR_A3_CfgChainOfCommand_Sizes_IBCT_name";
			nameShort = "$STR_A3_CfgChainOfCommand_Sizes_IBCT_nameShort";
			nameGender = "$STR_A3_CfgChainOfCommand_Sizes_IBCT_nameGender";
			textDefault = "$STR_A3_CfgChainOfCommand_Sizes_IBCT_textDefault";
			textShortDefault = "$STR_A3_CfgChainOfCommand_Sizes_IBCT_textShortDefault";
		};
		
		class HBCT : Brigade {
			name = "$STR_A3_CfgChainOfCommand_Sizes_HBCT_name";
			nameShort = "$STR_A3_CfgChainOfCommand_Sizes_HBCT_nameShort";
			nameGender = "$STR_A3_CfgChainOfCommand_Sizes_HBCT_nameGender";
			textDefault = "$STR_A3_CfgChainOfCommand_Sizes_HBCT_textDefault";
			textShortDefault = "$STR_A3_CfgChainOfCommand_Sizes_HBCT_textShortDefault";
		};
		
		class Division {
			size = 8;
			name = "$STR_A3_CfgChainOfCommand_Sizes_Division_name";
			nameShort = "$STR_A3_CfgChainOfCommand_Sizes_Division_nameShort";
			nameGender = "$STR_A3_CfgChainOfCommand_Sizes_Division_nameGender";
			commanderRank = "General";
			texture = "group_8";
			textDefault = "$STR_A3_CfgChainOfCommand_Sizes_Division_textDefault";
			textShortDefault = "$STR_A3_CfgChainOfCommand_Sizes_Division_textShortDefault";
		};
		
		class Corps {
			size = 9;
			name = "$STR_A3_CfgChainOfCommand_Sizes_Corps_name";
			nameShort = "$STR_A3_CfgChainOfCommand_Sizes_Corps_nameShort";
			nameGender = "$STR_A3_CfgChainOfCommand_Sizes_Corps_nameGender";
			commanderRank = "General";
			texture = "group_9";
			textDefault = "$STR_A3_CfgChainOfCommand_Sizes_Corps_textDefault";
			textShortDefault = "$STR_A3_CfgChainOfCommand_Sizes_Corps_textShortDefault";
		};
		
		class Army {
			size = 10;
			name = "$STR_A3_CfgChainOfCommand_Sizes_Army_name";
			nameShort = "$STR_A3_CfgChainOfCommand_Sizes_Army_nameShort";
			nameGender = "$STR_A3_CfgChainOfCommand_Sizes_Army_nameGender";
			commanderRank = "General";
			texture = "group_10";
			textDefault = "$STR_A3_CfgChainOfCommand_Sizes_Army_textDefault";
			textShortDefault = "$STR_A3_CfgChainOfCommand_Sizes_Army_textShortDefault";
		};
		
		class ArmyGroup {
			size = 11;
			name = "$STR_A3_CfgChainOfCommand_Sizes_ArmyGroup_name";
			nameShort = "$STR_A3_CfgChainOfCommand_Sizes_ArmyGroup_nameShort";
			nameGender = "$STR_A3_CfgChainOfCommand_Sizes_ArmyGroup_nameGender";
			commanderRank = "General";
			texture = "group_11";
			textDefault = "$STR_A3_CfgChainOfCommand_Sizes_ArmyGroup_textDefault";
			textShortDefault = "$STR_A3_CfgChainOfCommand_Sizes_ArmyGroup_textShortDefault";
		};
	};
	
	class Types {
		class Unknown {
			nameMasculine = "";
			nameFeminine = "";
			nameNeutral = "";
			texture = "unknown";
		};
		
		class Infantry {
			nameMasculine = "$STR_A3_CfgChainOfCommand_Types_Infantry_nameMasculine";
			nameFeminine = "$STR_A3_CfgChainOfCommand_Types_Infantry_nameFeminine";
			nameNeutral = "$STR_A3_CfgChainOfCommand_Types_Infantry_nameNeutral";
			texture = "inf";
		};
		
		class MotorizedInfantry {
			nameMasculine = "$STR_A3_CfgChainOfCommand_Types_MotorizedInfantry_nameMasculine";
			nameFeminine = "$STR_A3_CfgChainOfCommand_Types_MotorizedInfantry_nameFeminine";
			nameNeutral = "$STR_A3_CfgChainOfCommand_Types_MotorizedInfantry_nameNeutral";
			texture = "motor_inf";
		};
		
		class MechanizedInfantry {
			nameMasculine = "$STR_A3_CfgChainOfCommand_Types_MechanizedInfantry_nameMasculine";
			nameFeminine = "$STR_A3_CfgChainOfCommand_Types_MechanizedInfantry_nameFeminine";
			nameNeutral = "$STR_A3_CfgChainOfCommand_Types_MechanizedInfantry_nameNeutral";
			texture = "mech_inf";
		};
		
		class Armored {
			nameMasculine = "$STR_A3_CfgChainOfCommand_Types_Armored_nameMasculine";
			nameFeminine = "$STR_A3_CfgChainOfCommand_Types_Armored_nameFeminine";
			nameNeutral = "$STR_A3_CfgChainOfCommand_Types_Armored_nameNeutral";
			texture = "armor";
		};
		
		class Recon {
			nameMasculine = "$STR_A3_CfgChainOfCommand_Types_Recon_nameMasculine";
			nameFeminine = "$STR_A3_CfgChainOfCommand_Types_Recon_nameFeminine";
			nameNeutral = "$STR_A3_CfgChainOfCommand_Types_Recon_nameNeutral";
			texture = "recon";
		};
		
		class Cavalry {
			nameMasculine = "$STR_A3_CfgChainOfCommand_Types_Cavalry_nameMasculine";
			nameFeminine = "$STR_A3_CfgChainOfCommand_Types_Cavalry_nameFeminine";
			nameNeutral = "$STR_A3_CfgChainOfCommand_Types_Cavalry_nameNeutral";
			texture = "recon";
		};
		
		class Airborne {
			nameMasculine = "$STR_A3_CfgChainOfCommand_Types_Airborne_nameMasculine";
			nameFeminine = "$STR_A3_CfgChainOfCommand_Types_Airborne_nameFeminine";
			nameNeutral = "$STR_A3_CfgChainOfCommand_Types_Airborne_nameNeutral";
			texture = "inf";
		};
		
		class Helicopter {
			nameMasculine = "$STR_A3_CfgChainOfCommand_Types_Helicopter_nameMasculine";
			nameFeminine = "$STR_A3_CfgChainOfCommand_Types_Helicopter_nameFeminine";
			nameNeutral = "$STR_A3_CfgChainOfCommand_Types_Helicopter_nameNeutral";
			texture = "air";
		};
		
		class CombatAviation {
			nameMasculine = "$STR_A3_CfgChainOfCommand_Types_CombatAviation_nameMasculine";
			nameFeminine = "$STR_A3_CfgChainOfCommand_Types_CombatAviation_nameFeminine";
			nameNeutral = "$STR_A3_CfgChainOfCommand_Types_CombatAviation_nameNeutral";
			texture = "air";
		};
		
		class AttackRecon {
			nameMasculine = "$STR_A3_CfgChainOfCommand_Types_AttackRecon_nameMasculine";
			nameFeminine = "$STR_A3_CfgChainOfCommand_Types_AttackRecon_nameFeminine";
			nameNeutral = "$STR_A3_CfgChainOfCommand_Types_AttackRecon_nameNeutral";
			texture = "air";
		};
		
		class GeneralSupport {
			nameMasculine = "$STR_A3_CfgChainOfCommand_Types_GeneralSupport_nameMasculine";
			nameFeminine = "$STR_A3_CfgChainOfCommand_Types_GeneralSupport_nameFeminine";
			nameNeutral = "$STR_A3_CfgChainOfCommand_Types_GeneralSupport_nameNeutral";
			texture = "air";
		};
		
		class Assault {
			nameMasculine = "$STR_A3_CfgChainOfCommand_Types_Assault_nameMasculine";
			nameFeminine = "$STR_A3_CfgChainOfCommand_Types_Assault_nameFeminine";
			nameNeutral = "$STR_A3_CfgChainOfCommand_Types_Assault_nameNeutral";
			texture = "air";
		};
		
		class AviationSupport {
			nameMasculine = "$STR_A3_CfgChainOfCommand_Types_AviationSupport_nameMasculine";
			nameFeminine = "$STR_A3_CfgChainOfCommand_Types_AviationSupport_nameFeminine";
			nameNeutral = "$STR_A3_CfgChainOfCommand_Types_AviationSupport_nameNeutral";
			texture = "air";
		};
		
		class Fighter {
			nameMasculine = "$STR_A3_CfgChainOfCommand_Types_Fighter_nameMasculine";
			nameFeminine = "$STR_A3_CfgChainOfCommand_Types_Fighter_nameFeminine";
			nameNeutral = "$STR_A3_CfgChainOfCommand_Types_Fighter_nameNeutral";
			texture = "plane";
		};
		
		class UAV {
			nameMasculine = "$STR_A3_CfgChainOfCommand_Types_UAV_nameMasculine";
			nameFeminine = "$STR_A3_CfgChainOfCommand_Types_UAV_nameFeminine";
			nameNeutral = "$STR_A3_CfgChainOfCommand_Types_UAV_nameNeutral";
			texture = "uav";
		};
		
		class Medical {
			nameMasculine = "$STR_A3_CfgChainOfCommand_Types_Medical_nameMasculine";
			nameFeminine = "$STR_A3_CfgChainOfCommand_Types_Medical_nameFeminine";
			nameNeutral = "$STR_A3_CfgChainOfCommand_Types_Medical_nameNeutral";
			texture = "med";
		};
		
		class Artillery {
			nameMasculine = "$STR_A3_CfgChainOfCommand_Types_Artillery_nameMasculine";
			nameFeminine = "$STR_A3_CfgChainOfCommand_Types_Artillery_nameFeminine";
			nameNeutral = "$STR_A3_CfgChainOfCommand_Types_Artillery_nameNeutral";
			texture = "art";
		};
		
		class Mortar {
			nameMasculine = "$STR_A3_CfgChainOfCommand_Types_Mortar_nameMasculine";
			nameFeminine = "$STR_A3_CfgChainOfCommand_Types_Mortar_nameFeminine";
			nameNeutral = "$STR_A3_CfgChainOfCommand_Types_Mortar_nameNeutral";
			texture = "mortar";
		};
		
		class HQ {
			nameMasculine = "$STR_A3_CfgChainOfCommand_Types_HQ_nameMasculine";
			nameFeminine = "$STR_A3_CfgChainOfCommand_Types_HQ_nameFeminine";
			nameNeutral = "$STR_A3_CfgChainOfCommand_Types_HQ_nameNeutral";
			texture = "hq";
		};
		
		class Support {
			nameMasculine = "$STR_A3_CfgChainOfCommand_Types_Support_nameMasculine";
			nameFeminine = "$STR_A3_CfgChainOfCommand_Types_Support_nameFeminine";
			nameNeutral = "$STR_A3_CfgChainOfCommand_Types_Support_nameNeutral";
			texture = "support";
		};
		
		class Maintenance {
			nameMasculine = "$STR_A3_CfgChainOfCommand_Types_Maintenance_nameMasculine";
			nameFeminine = "$STR_A3_CfgChainOfCommand_Types_Maintenance_nameFeminine";
			nameNeutral = "$STR_A3_CfgChainOfCommand_Types_Maintenance_nameNeutral";
			texture = "maint";
		};
		
		class Service {
			nameMasculine = "$STR_A3_CfgChainOfCommand_Types_Service_nameMasculine";
			nameFeminine = "$STR_A3_CfgChainOfCommand_Types_Service_nameFeminine";
			nameNeutral = "$STR_A3_CfgChainOfCommand_Types_Service_nameNeutral";
			texture = "service";
		};
		
		class Maritime {
			nameMasculine = "$STR_A3_CfgChainOfCommand_Types_Maritime_nameMasculine";
			nameFeminine = "$STR_A3_CfgChainOfCommand_Types_Maritime_nameFeminine";
			nameNeutral = "$STR_A3_CfgChainOfCommand_Types_Maritime_nameNeutral";
			texture = "naval";
		};
	};
};
