// Generated by unRap v1.06 by Kegetys

class CfgCommunicationMenu {
	class Default {
		text = "";
		submenu = "";
		expression = "";
		icon = "\a3\Ui_f\data\GUI\Cfg\CommunicationMenu\call_ca.paa";
		iconText = "";
		cursor = "";
		enable = "";
	};
	
	class A {
		text = $STR_A3_RADIO_A;
		iconText = "A";
		expression = "%1";
	};
	
	class B {
		text = $STR_A3_RADIO_B;
		iconText = "B";
		expression = "%1";
	};
	
	class C {
		text = $STR_A3_RADIO_C;
		iconText = "C";
		expression = "%1";
	};
	
	class D {
		text = $STR_A3_RADIO_D;
		iconText = "D";
		expression = "%1";
	};
	
	class E {
		text = $STR_A3_RADIO_E;
		iconText = "E";
		expression = "%1";
	};
	
	class F {
		text = $STR_A3_RADIO_F;
		iconText = "F";
		expression = "%1";
	};
	
	class G {
		text = $STR_A3_RADIO_G;
		iconText = "G";
		expression = "%1";
	};
	
	class H {
		text = $STR_A3_RADIO_H;
		iconText = "H";
		expression = "%1";
	};
	
	class I {
		text = $STR_A3_RADIO_I;
		iconText = "I";
		expression = "%1";
	};
	
	class J {
		text = $STR_A3_RADIO_J;
		iconText = "J";
		expression = "%1";
	};
	
	class K {
		text = $STR_A3_RADIO_K;
		iconText = "K";
		expression = "%1";
	};
	
	class L {
		text = $STR_A3_RADIO_L;
		iconText = "L";
		expression = "%1";
	};
	
	class M {
		text = $STR_A3_RADIO_M;
		iconText = "M";
		expression = "%1";
	};
	
	class N {
		text = $STR_A3_RADIO_N;
		iconText = "N";
		expression = "%1";
	};
	
	class O {
		text = $STR_A3_RADIO_O;
		iconText = "O";
		expression = "%1";
	};
	
	class P {
		text = $STR_A3_RADIO_P;
		iconText = "P";
		expression = "%1";
	};
	
	class Q {
		text = $STR_A3_RADIO_Q;
		iconText = "Q";
		expression = "%1";
	};
	
	class R {
		text = $STR_A3_RADIO_R;
		iconText = "R";
		expression = "%1";
	};
	
	class S {
		text = $STR_A3_RADIO_S;
		iconText = "S";
		expression = "%1";
	};
	
	class T {
		text = $STR_A3_RADIO_T;
		iconText = "T";
		expression = "%1";
	};
	
	class U {
		text = $STR_A3_RADIO_U;
		iconText = "U";
		expression = "%1";
	};
	
	class V {
		text = $STR_A3_RADIO_V;
		iconText = "V";
		expression = "%1";
	};
	
	class W {
		text = $STR_A3_RADIO_W;
		iconText = "W";
		expression = "%1";
	};
	
	class X {
		text = $STR_A3_RADIO_X;
		iconText = "X";
		expression = "%1";
	};
	
	class Y {
		text = $STR_A3_RADIO_Y;
		iconText = "Y";
		expression = "%1";
	};
	
	class Z {
		text = $STR_A3_RADIO_Z;
		iconText = "Z";
		expression = "%1";
	};
	
	class Call {
		text = "$STR_A3_CfgCommunicationMenu_Call_0";
		icon = "\a3\Ui_f\data\GUI\Cfg\CommunicationMenu\call_ca.paa";
		expression = "%1";
	};
	
	class Attack {
		text = "$STR_A3_CfgCommunicationMenu_Attack_0";
		icon = "\a3\Ui_f\data\GUI\Cfg\CommunicationMenu\attack_ca.paa";
		expression = "%1";
	};
	
	class Defend {
		text = "$STR_A3_CfgCommunicationMenu_Defend_0";
		icon = "\a3\Ui_f\data\GUI\Cfg\CommunicationMenu\defend_ca.paa";
		expression = "%1";
	};
	
	class ArtilleryBase {
		text = "$STR_A3_mdl_supp_disp_artillery";
		icon = "\a3\Ui_f\data\GUI\Cfg\CommunicationMenu\artillery_ca.paa";
		cursor = "\A3\ui_f\data\igui\cfg\cursors\iconCursorSupport_ca.paa";
	};
	
	class MortarBase {
		icon = "\a3\Ui_f\data\GUI\Cfg\CommunicationMenu\mortar_ca.paa";
		cursor = "\A3\ui_f\data\igui\cfg\cursors\iconCursorSupport_ca.paa";
	};
	
	class CASBase {
		icon = "\a3\Ui_f\data\GUI\Cfg\CommunicationMenu\cas_ca.paa";
		cursor = "\A3\ui_f\data\igui\cfg\cursors\iconCursorSupport_ca.paa";
	};
	
	class SupplyDropBase {
		text = "$STR_A3_mdl_supp_disp_drop";
		icon = "\a3\Ui_f\data\GUI\Cfg\CommunicationMenu\supplydrop_ca.paa";
		cursor = "\A3\ui_f\data\igui\cfg\cursors\iconCursorSupport_ca.paa";
	};
	
	class TransportBase {
		text = "$STR_A3_mdl_supp_disp_transport";
		icon = "\a3\Ui_f\data\GUI\Cfg\CommunicationMenu\transport_ca.paa";
		cursor = "\A3\ui_f\data\igui\cfg\cursors\iconCursorSupport_ca.paa";
	};
};
