// Generated by unRap v1.06 by Kegetys

class RscDisplayOptionsVideo {
	onLoad = "[""onLoad"",_this,""RscDisplayOptionsVideo"",'GUI'] call compile preprocessfilelinenumbers ""A3\ui_f\scripts\initDisplay.sqf""";
	onUnload = "[""onUnload"",_this,""RscDisplayOptionsVideo"",'GUI'] call compile preprocessfilelinenumbers ""A3\ui_f\scripts\initDisplay.sqf""";
	movingEnable = 0;
	enableDisplay = 1;
	
	class ControlsBackground {
		class TitleBackground : RscText {
			colorBackground[] = {"(profilenamespace getvariable ['GUI_BCG_RGB_R',0.69])", "(profilenamespace getvariable ['GUI_BCG_RGB_G',0.75])", "(profilenamespace getvariable ['GUI_BCG_RGB_B',0.5])", "(profilenamespace getvariable ['GUI_BCG_RGB_A',0.8])"};
			idc = 1080;
			x = "1 * 			(			((safezoneW / safezoneH) min 1.2) / 40) + 			(safezoneX)";
			y = "1 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25) + 			(safezoneY + safezoneH - 			(			((safezoneW / safezoneH) min 1.2) / 1.2))";
			w = "38 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
			h = "1 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
		};
		
		class OverallQualityBackground : RscText {
			colorBackground[] = {0, 0, 0, 0.7};
			idc = 1082;
			x = "1 * 			(			((safezoneW / safezoneH) min 1.2) / 40) + 			(safezoneX)";
			y = "2.1 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25) + 			(safezoneY + safezoneH - 			(			((safezoneW / safezoneH) min 1.2) / 1.2))";
			w = "38 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
			h = "1 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
		};
		
		class MainBackground : RscText {
			colorBackground[] = {0, 0, 0, 0.7};
			idc = 1083;
			x = "1 * 			(			((safezoneW / safezoneH) min 1.2) / 40) + 			(safezoneX)";
			y = "3.2 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25) + 			(safezoneY + safezoneH - 			(			((safezoneW / safezoneH) min 1.2) / 1.2))";
			w = "38 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
			h = "19.7 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
		};
		
		class TabsBackgroundLeft : RscText {
			colorBackground[] = {0, 0, 0, 1};
			idc = 1081;
			x = "1 * 			(			((safezoneW / safezoneH) min 1.2) / 40) + 			(safezoneX)";
			y = "3.2 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25) + 			(safezoneY + safezoneH - 			(			((safezoneW / safezoneH) min 1.2) / 1.2))";
			w = "38 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
			h = "1 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
		};
	};
	
	class Controls {
		class B_OK {};
		class B_Cancel {};
		class B_Default {};
		class TextRefresh {};
		class ValueRefresh {};
		class TextTextureDetail {};
		class ValueTextureDetail {};
		class TextQualityPreference {};
		class ValueQualityPreference {};
		class TextShadingDetail {};
		class ValueShadingDetail {};
		class TextShadowDetail {};
		class ValueShadowDetail {};
		class TextTerrain {};
		class ValueTerrain {};
		class TextObjectShadows {};
		class ValueObjectShadows {};
		class TextHDRDetail {};
		class ValueHDRDetail {};
		class TextVsync {};
		class ValueVsync {};
		class TextAnisotropicDetail {};
		class ValueAnisotropicDetail {};
		class TextPostprocessEffects {};
		class ValuePostprocessEffects {};
		class TextAntialiasing {};
		class ValueAntialiasing {};
		class TextWBuffer {};
		class ValueWBuffer {};
		class TextAspectRatio {};
		class ValueAspectRatio {};
		class TextResolution {};
		class ValueResolution {};
		class ValueObjectsDetail {};
		class TextLanguage {};
		class ValueLanguage {};
		class ValueIGUISize {};
		class TextIGUISize {};
		class TextBrightness {};
		class ValueBrightness {};
		class SliderBrightness {};
		class TextGamma {};
		class ValueGamma {};
		class SliderGamma {};
		class SliderVisibility {};
		class ValueVisibility {};
		class TextVisibility {};
		class ValueFXAADetail {};
		class TextPIPDetail {};
		class ValuePIPDetail {};
		class TextSWDetail {};
		class ValueSWDetail {};
		class TextShadowVisibility {};
		class ValueShadowVisibility {};
		class SliderShadowVisibility {};
		class TextObjectsDetail {};
		
		class Title : RscTitle {
			colorBackground[] = {0, 0, 0, 0};
			style = 0;
			idc = 1000;
			text = $STR_DISP_OPTIONS_VIDEO;
			x = "1 * 			(			((safezoneW / safezoneH) min 1.2) / 40) + 			(safezoneX)";
			y = "1 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25) + 			(safezoneY + safezoneH - 			(			((safezoneW / safezoneH) min 1.2) / 1.2))";
			w = "15 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
			h = "1 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
		};
		
		class PlayersName : Title {
			idc = 8434;
			style = 1;
			colorBackground[] = {0, 0, 0, 0};
			x = "16 * 			(			((safezoneW / safezoneH) min 1.2) / 40) + 			(safezoneX)";
			y = "1 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25) + 			(safezoneY + safezoneH - 			(			((safezoneW / safezoneH) min 1.2) / 1.2))";
			w = "23 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
			h = "1 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
		};
		
		class CA_TextQualityPreference : RscText {
			style = 0;
			shadow = false;
			idc = 1002;
			text = "$STR_A3_RscDisplayOptionsVideo_CA_TextQualityPreference";
			x = "1 * 			(			((safezoneW / safezoneH) min 1.2) / 40) + 			(safezoneX)";
			y = "2.1 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25) + 			(safezoneY + safezoneH - 			(			((safezoneW / safezoneH) min 1.2) / 1.2))";
			w = "8 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
			h = "1 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
		};
		
		class CA_ValueQualityPreference : RscCombo {
			idc = 126;
			x = "9 * 			(			((safezoneW / safezoneH) min 1.2) / 40) + 			(safezoneX)";
			y = "2.1 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25) + 			(safezoneY + safezoneH - 			(			((safezoneW / safezoneH) min 1.2) / 1.2))";
			w = "8 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
			h = "1 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
			tooltip = "$STR_A3_RscDisplayOptionsVideo_CA_ValueQualityPreference_tooltip";
		};
		
		class TextFPS : RscText {
			idc = 1400;
			style = 1;
			shadow = false;
			text = "$STR_A3_RscDisplayOptionsVideo_TextFPS";
			x = "35 * 			(			((safezoneW / safezoneH) min 1.2) / 40) + 			(safezoneX)";
			y = "2.1 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25) + 			(safezoneY + safezoneH - 			(			((safezoneW / safezoneH) min 1.2) / 1.2))";
			w = "4 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
			h = "1 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
			tooltip = "$STR_A3_RscDisplayOptionsVideo_TextFPS_tooltip";
		};
		
		class GeneralButton : RscButtonMenu {
			IDC = 8431;
			colorBackground[] = {0, 0, 0, 0};
			text = "$STR_A3_RscDisplayOptionsVideo_GeneralButton";
			x = "1 * 			(			((safezoneW / safezoneH) min 1.2) / 40) + 			(safezoneX)";
			y = "3.2 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25) + 			(safezoneY + safezoneH - 			(			((safezoneW / safezoneH) min 1.2) / 1.2))";
			w = "8 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
			h = "1 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
			tooltip = "$STR_A3_RscDisplayOptionsVideo_GeneralButton_tooltip";
		};
		
		class DisplayButton : RscButtonMenu {
			IDC = 8433;
			colorBackground[] = {0, 0, 0, 0};
			text = "$STR_A3_RscDisplayOptionsVideo_DisplayButton";
			x = "9 * 			(			((safezoneW / safezoneH) min 1.2) / 40) + 			(safezoneX)";
			y = "3.2 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25) + 			(safezoneY + safezoneH - 			(			((safezoneW / safezoneH) min 1.2) / 1.2))";
			w = "8 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
			h = "1 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
			tooltip = "$STR_A3_RscDisplayOptionsVideo_DisplayButton_tooltip";
		};
		
		class AAPPButton : RscButtonMenu {
			IDC = 8432;
			colorBackground[] = {0, 0, 0, 0};
			text = "$STR_A3_RscDisplayOptionsVideo_AAPPButton";
			x = "17 * 			(			((safezoneW / safezoneH) min 1.2) / 40) + 			(safezoneX)";
			y = "3.2 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25) + 			(safezoneY + safezoneH - 			(			((safezoneW / safezoneH) min 1.2) / 1.2))";
			w = "8 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
			h = "1 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
			tooltip = "$STR_A3_RscDisplayOptionsVideo_AAPPButton_tooltip";
		};
		
		class Video_OK : RscButtonMenuOK {
			x = "32.75 * 			(			((safezoneW / safezoneH) min 1.2) / 40) + 			(safezoneX)";
			y = "23 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25) + 			(safezoneY + safezoneH - 			(			((safezoneW / safezoneH) min 1.2) / 1.2))";
			w = "6.25 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
			h = "1 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
		};
		
		class Video_Cancel : RscButtonMenuCancel {
			x = "1 * 			(			((safezoneW / safezoneH) min 1.2) / 40) + 			(safezoneX)";
			y = "23 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25) + 			(safezoneY + safezoneH - 			(			((safezoneW / safezoneH) min 1.2) / 1.2))";
			w = "6.25 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
			h = "1 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
		};
		
		class VideoAutodetect : RscButtonMenu {
			idc = 1291;
			text = "$STR_A3_RscDisplayOptionsVideo_VideoAutodetect";
			x = "7.35 * 			(			((safezoneW / safezoneH) min 1.2) / 40) + 			(safezoneX)";
			y = "23 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25) + 			(safezoneY + safezoneH - 			(			((safezoneW / safezoneH) min 1.2) / 1.2))";
			w = "6.25 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
			h = "1 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
			tooltip = "$STR_A3_RscDisplayOptionsVideo_VideoAutodetect_tooltip";
		};
		
		class HideDialog : RscButtonMenu {
			shortcuts[] = {0x00050000 + 3, 35};
			idc = 2406;
			text = $STR_CA_HIDE;
			x = "13.7 * 			(			((safezoneW / safezoneH) min 1.2) / 40) + 			(safezoneX)";
			y = "23 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25) + 			(safezoneY + safezoneH - 			(			((safezoneW / safezoneH) min 1.2) / 1.2))";
			w = "6.25 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
			h = "1 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
			tooltip = "$STR_A3_RscDisplayOptionsVideo_HideDialog_tooltip";
		};
		
		class BasicGroup : RscControlsGroup {
			class VScrollbar : VScrollbar {
				width = 0;
			};
			
			class HScrollbar : HScrollbar {
				height = 0;
			};
			idc = 2300;
			x = "1 * 			(			((safezoneW / safezoneH) min 1.2) / 40) + 			(safezoneX)";
			y = "4.7 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25) + 			(safezoneY + safezoneH - 			(			((safezoneW / safezoneH) min 1.2) / 1.2))";
			w = "38 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
			h = "18.2 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
			
			class controls {
				class EmptyText : RscText {
					idc = -1;
					x = "0 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					y = "0 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
					w = "1 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					h = "1 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
				};
				
				class CA_TextFillRate : RscText {
					style = 1;
					shadow = false;
					idc = 1018;
					text = "$STR_A3_RscDisplayOptionsVideo_CA_TextFillRate";
					x = "0 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					y = "1.5 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
					w = "8 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					h = "1 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
				};
				
				class CA_ValueFillRate : RscCombo {
					idc = 1234;
					wholeHeight = "15 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
					x = "8 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					y = "1.5 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
					w = "8 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					h = "1 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
					tooltip = "$STR_A3_RscDisplayOptionsVideo_CA_ValueFillRate_tooltip";
				};
				
				class PerformanceWarning : RscPictureKeepAspect {
					idc = 1401;
					text = "\A3\Ui_f\data\GUI\Rsc\RscDisplayOptionsVideo\icon_performance.paa";
					x = "16.2 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					y = "1.5 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
					w = "1 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					h = "1 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
					tooltip = $STR_A3_RSCDISPLAYOPTIONSVIDEO_PERFORMANCEWARNING;
				};
				
				class CA_TextTextureDetail : CA_TextFillRate {
					idc = 1037;
					text = "$STR_A3_RscDisplayOptionsVideo_CA_TextTextureDetail";
					x = "0 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					y = "2.8 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
					w = "8 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					h = "1 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
				};
				
				class CA_ValueTextureDetail : RscCombo {
					idc = 125;
					x = "8 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					y = "2.8 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
					w = "8 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					h = "1 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
					tooltip = "$STR_A3_RscDisplayOptionsVideo_CA_ValueTextureDetail_tooltip";
				};
				
				class CA_TextObjectsDetail : CA_TextFillRate {
					idc = 1030;
					text = "$STR_A3_RscDisplayOptionsVideo_CA_TextObjectsDetail";
					x = "0 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					y = "4.1 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
					w = "8 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					h = "1 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
				};
				
				class CA_ValueObjectsDetail : CA_ValueTextureDetail {
					idc = 124;
					x = "8 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					y = "4.1 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
					w = "8 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					h = "1 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
					tooltip = "$STR_A3_RscDisplayOptionsVideo_CA_ValueObjectsDetail_tooltip";
				};
				
				class TextTerrain1 : CA_TextFillRate {
					idc = 1029;
					text = "$STR_A3_RscDisplayOptionsVideo_TextTerrain1";
					x = "0 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					y = "5.4 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
					w = "8 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					h = "1 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
				};
				
				class ValueTerrain1 : CA_ValueTextureDetail {
					idc = 123;
					rows = 4;
					x = "8 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					y = "5.4 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
					w = "8 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					h = "1 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
					tooltip = "$STR_A3_RscDisplayOptionsVideo_ValueTerrain1_tooltip";
				};
				
				class CA_TextShadowDetail : CA_TextFillRate {
					idc = 1031;
					text = "$STR_A3_RscDisplayOptionsVideo_CA_TextShadowDetail";
					x = "0 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					y = "7.7 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
					w = "8 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					h = "1 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
				};
				
				class CA_ValueShadowDetail : CA_ValueTextureDetail {
					idc = 128;
					x = "8 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					y = "7.7 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
					w = "8 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					h = "1 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
					tooltip = "$STR_A3_RscDisplayOptionsVideo_CA_ValueShadowDetail_tooltip";
				};
				
				class CA_TextParticlesQuality : CA_TextFillRate {
					idc = 1033;
					text = "$STR_A3_RscDisplayOptionsVideo_CA_TextParticlesQuality";
					x = "0 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					y = "9 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
					w = "8 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					h = "1 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
				};
				
				class CA_ValueParticlesQuality : CA_ValueTextureDetail {
					idc = 143;
					x = "8 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					y = "9 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
					w = "8 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					h = "1 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
					tooltip = "$STR_A3_RscDisplayOptionsVideo_CA_ValueParticlesQuality_tooltip";
				};
				
				class CA_TextSWDetail : CA_TextFillRate {
					idc = 1032;
					text = "$STR_A3_RscDisplayOptionsVideo_CA_TextSWDetail";
					x = "0 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					y = "10.3 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
					w = "8 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					h = "1 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
				};
				
				class CA_ValueSWDetail : CA_ValueTextureDetail {
					idc = 335;
					rows = 2;
					x = "8 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					y = "10.3 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
					w = "8 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					h = "1 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
					tooltip = "$STR_A3_RscDisplayOptionsVideo_CA_ValueSWDetail_tooltip";
				};
				
				class CA_TextPIPDetail : CA_TextFillRate {
					idc = 1025;
					text = "$STR_A3_RscDisplayOptionsVideo_CA_TextPIPDetail";
					x = "0 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					y = "11.6 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
					w = "8 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					h = "1 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
				};
				
				class CA_ValuePIPDetail : CA_ValueFillRate {
					idc = 334;
					wholeHeight = "6 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
					x = "8 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					y = "11.6 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
					w = "8 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					h = "1 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
					tooltip = "$STR_A3_RscDisplayOptionsVideo_CA_ValuePIPDetail_tooltip";
				};
				
				class CA_TextHDRDetail : CA_TextFillRate {
					idc = 1021;
					text = "$STR_A3_RscDisplayOptionsVideo_CA_TextHDRDetail";
					x = "0 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					y = "13.9 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
					w = "8 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					h = "1 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
				};
				
				class CA_ValueHDRDetail : CA_ValueFillRate {
					idc = 131;
					x = "8 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					y = "13.9 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
					w = "8 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					h = "1 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
					tooltip = "$STR_A3_RscDisplayOptionsVideo_CA_ValueHDRDetail_tooltip";
				};
				
				class CA_TextDynamicLights : CA_TextFillRate {
					idc = 1026;
					text = "$STR_A3_RscDisplayOptionsVideo_CA_TextDynamicLights";
					x = "0 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					y = "15.2 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
					w = "8 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					h = "1 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
				};
				
				class CA_ValueDynamicLights : CA_ValueFillRate {
					idc = 144;
					wholeHeight = "3 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
					x = "8 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					y = "15.2 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
					w = "8 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					h = "1 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
					tooltip = "$STR_A3_RscDisplayOptionsVideo_CA_ValueDynamicLights_tooltip";
				};
				
				class TextVisibility : RscText {
					style = 0;
					idc = 1017;
					text = "$STR_A3_RscDisplayOptionsVideo_TextVisibility";
					x = "20.8 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					y = "0 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
					w = "17.2 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					h = "1 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
					colorBackground[] = {0, 0, 0, 1};
				};
				
				class CA_TextOverallX : CA_TextFillRate {
					idc = 1007;
					text = "$STR_A3_RscDisplayOptionsVideo_CA_TextOverallX";
					x = "20.7 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					y = "1.5 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
					w = "5 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					h = "1 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
				};
				
				class CA_ValueVisibility : RscEdit {
					idc = 103;
					style = 0;
					shadow = false;
					maxChars = 5;
					x = "33.9 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					y = "1.5 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
					w = "3.1 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					h = "1 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
				};
				
				class CA_SliderVisibility : RscXSliderH {
					idc = 104;
					x = "25.7 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					y = "1.5 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
					w = "8 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					h = "1 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
					tooltip = "$STR_A3_RscDisplayOptionsVideo_CA_SliderVisibility_tooltip";
				};
				
				class CA_TextObjectVisibility : CA_TextFillRate {
					idc = 1009;
					text = "$STR_A3_RscDisplayOptionsVideo_CA_TextObjectVisibility";
					x = "20.7 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					y = "2.8 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
					w = "5 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					h = "1 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
				};
				
				class CA_ValueObjectVisibility : RscEdit {
					idc = 308;
					style = 0;
					shadow = false;
					maxChars = 5;
					text = "$STR_A3_RscDisplayOptionsVideo_CA_ValueObjectVisibility";
					x = "33.9 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					y = "2.8 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
					w = "3.1 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					h = "1 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
				};
				
				class CA_SliderObjectVisibility : RscXSliderH {
					idc = 309;
					x = "25.7 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					y = "2.8 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
					w = "8 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					h = "1 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
					tooltip = "$STR_A3_RscDisplayOptionsVideo_CA_SliderObjectVisibility_tooltip";
				};
				
				class CA_TextShadowVisibility : CA_TextFillRate {
					idc = 313;
					text = "$STR_A3_RscDisplayOptionsVideo_CA_TextShadowVisibility";
					x = "20.7 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					y = "4.1 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
					w = "5 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					h = "1 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
				};
				
				class CA_ValueShadowVisibility : RscEdit {
					idc = 311;
					style = 0;
					shadow = false;
					maxChars = 5;
					text = "$STR_A3_RscDisplayOptionsVideo_CA_ValueShadowVisibility";
					x = "33.9 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					y = "4.1 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
					w = "3.1 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					h = "1 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
				};
				
				class CA_SliderShadowVisibility : RscXSliderH {
					idc = 312;
					x = "25.7 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					y = "4.1 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
					w = "8 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					h = "1 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
					tooltip = "$STR_A3_RscDisplayOptionsVideo_CA_SliderShadowVisibility_tooltip";
				};
				
				class TextQuality : RscText {
					style = 1;
					idc = 1046;
					text = "$STR_A3_RscDisplayOptionsVideo_TextQuality";
					x = "0 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					y = "0 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
					w = "8 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					h = "1 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
					colorBackground[] = {0, 0, 0, 1};
				};
			};
		};
		
		class QualityGroup : RscControlsGroup {
			class VScrollbar : VScrollbar {
				width = 0;
			};
			
			class HScrollbar : HScrollbar {
				height = 0;
			};
			idc = 2302;
			x = "1 * 			(			((safezoneW / safezoneH) min 1.2) / 40) + 			(safezoneX)";
			y = "4.7 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25) + 			(safezoneY + safezoneH - 			(			((safezoneW / safezoneH) min 1.2) / 1.2))";
			w = "38 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
			h = "18.2 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
			
			class controls {
				class CA_TextDisplayMode : RscText {
					style = 1;
					shadow = false;
					idc = 1028;
					text = "$STR_A3_RscDisplayOptionsVideo_CA_TextDisplayMode";
					x = "0 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					y = "0 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
					w = "8 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					h = "1 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
				};
				
				class CA_ValueDisplayMode : RscCombo {
					idc = 1131;
					x = "8 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					y = "0 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
					w = "8 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					h = "1 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
					tooltip = "$STR_A3_RscDisplayOptionsVideo_CA_ValueDisplayMode_tooltip";
				};
				
				class CA_TextResolution : CA_TextDisplayMode {
					style = 1;
					idc = 1013;
					text = $STR_DISP_OPT_RESOLUTION_NEW;
					x = "0 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					y = "1.5 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
					w = "8 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					h = "1 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
				};
				
				class CA_ValueResolution : RscCombo {
					idc = 113;
					wholeHeight = "15 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
					x = "8 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					y = "1.5 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
					w = "8 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					h = "1 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
					tooltip = "$STR_A3_RscDisplayOptionsVideo_CA_ValueResolution_tooltip";
				};
				
				class CA_TextAspectRatio : CA_TextDisplayMode {
					idc = 1015;
					text = $STR_DISP_OPT_ASPECT_RATIO;
					x = "0 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					y = "3 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
					w = "8 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					h = "1 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
				};
				
				class CA_ValueAspectRatio : CA_ValueResolution {
					idc = 134;
					x = "8 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					y = "3 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
					w = "8 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					h = "1 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
					tooltip = "$STR_A3_RscDisplayOptionsVideo_CA_ValueAspectRatio_tooltip";
				};
				
				class CA_TextVsync : CA_TextDisplayMode {
					idc = 1022;
					text = "$STR_A3_RscDisplayOptionsVideo_CA_TextVsync";
					x = "0 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					y = "4.5 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
					w = "8 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					h = "1 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
				};
				
				class CA_ValueVsync : CA_ValueResolution {
					idc = 140;
					x = "8 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					y = "4.5 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
					w = "8 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					h = "1 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
					tooltip = "$STR_A3_RscDisplayOptionsVideo_CA_ValueVsync_tooltip";
				};
				
				class CA_TextIGUISize : CA_TextDisplayMode {
					style = 1;
					idc = 1014;
					text = $STR_OPT_VIDEO_UISIZE;
					x = "0 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					y = "6 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
					w = "8 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					h = "1 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
				};
				
				class CA_ValueIGUISize : CA_ValueResolution {
					idc = 136;
					x = "8 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					y = "6 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
					w = "8 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					h = "1 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
					tooltip = "$STR_A3_RscDisplayOptionsVideo_CA_ValueIGUISize_tooltip";
				};
				
				class CA_TextBrightness : CA_TextDisplayMode {
					style = 1;
					idc = 1003;
					text = $STR_DISP_OPT_BRIGHT;
					x = "0 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					y = "8.5 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
					w = "8 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					h = "1 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
				};
				
				class CA_SliderBrightness : RscXSliderH {
					idc = 112;
					x = "8 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					y = "8.5 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
					w = "8 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					h = "1 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
					tooltip = "$STR_A3_RscDisplayOptionsVideo_CA_SliderBrightness_tooltip";
				};
				
				class CA_ValueBrightness : RscEdit {
					idc = 111;
					style = 0;
					maxChars = 3;
					x = "16.2 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					y = "8.5 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
					w = "2.5 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					h = "1 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
				};
				
				class CA_TextGamma : CA_TextDisplayMode {
					idc = 1005;
					text = $STR_DISP_OPT_GAMMA;
					x = "0 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					y = "10 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
					w = "8 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					h = "1 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
				};
				
				class CA_SliderGamma : CA_SliderBrightness {
					idc = 110;
					x = "8 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					y = "10 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
					w = "8 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					h = "1 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
					tooltip = "$STR_A3_RscDisplayOptionsVideo_CA_SliderGamma_tooltip";
				};
				
				class CA_ValueGamma : RscEdit {
					idc = 109;
					style = 0;
					maxChars = 3;
					x = "16.2 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					y = "10 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
					w = "2.5 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					h = "1 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
				};
				
				class PictureGammaTest : RscPicture {
					idc = 1202;
					text = "\A3\Ui_f\data\GUI\Rsc\RscDisplayOptionsVideo\GammaTestImage_gs.paa";
					x = "9.2 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					y = "11.1 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
					w = "5.6 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					h = "2.8 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
					tooltip = $STR_A3_RSCDISPLAYOPTIONSVIDEO_PICTUREGAMMATEST;
				};
				
				class CA_PictureAspectRatioBackground : RscPictureKeepAspect {
					idc = 1200;
					text = "\A3\ui_f\data\GUI\Rsc\RscDisplayOptionsVideo\aspect_circle_gr.paa";
					x = "25.5 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					y = "0 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
					w = "6 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					h = "6 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
					colorText[] = {0, 0, 0, 1};
				};
				
				class CA_PictureAspectRatio : RscPicture {
					h = "(6 * 			(			((safezoneW / safezoneH) min 1.2) / 40)) * 4/3";
					idc = 1201;
					text = "\A3\ui_f\data\GUI\Rsc\RscDisplayOptionsVideo\aspect_circle_gr.paa";
					x = "25.5 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					y = "0 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
					w = "6 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
				};
				
				class CA_PictureAspectRatioText : CA_TextDisplayMode {
					style = 0;
					idc = 1016;
					text = "$STR_A3_RscDisplayOptionsVideo_CA_PictureAspectRatioText";
					x = "21 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					y = "6 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
					w = "16 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					h = "1 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
					colorBackground[] = {0, 0, 0, 1};
				};
			};
		};
		
		class RenderingGroup : RscControlsGroup {
			class VScrollbar : VScrollbar {
				width = 0;
			};
			
			class HScrollbar : HScrollbar {
				height = 0;
			};
			idc = 2301;
			x = "1 * 			(			((safezoneW / safezoneH) min 1.2) / 40) + 			(safezoneX)";
			y = "4.7 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25) + 			(safezoneY + safezoneH - 			(			((safezoneW / safezoneH) min 1.2) / 1.2))";
			w = "38 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
			h = "18.2 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
			
			class controls {
				class TextPostprocesses : RscText {
					style = 1;
					idc = 1036;
					text = "$STR_A3_RscDisplayOptionsVideo_TextPostprocesses";
					x = "0 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					y = "0 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
					w = "8 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					h = "1 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
					colorBackground[] = {0, 0, 0, 1};
				};
				
				class TextBloom : RscText {
					style = 1;
					shadow = false;
					idc = 1039;
					text = "$STR_A3_RscDisplayOptionsVideo_TextBloom";
					x = "0 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					y = "1.5 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
					w = "8 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					h = "1 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
				};
				
				class ValueBloom : RscXSliderH {
					idc = 1311;
					x = "8 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					y = "1.5 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
					w = "8 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					h = "1 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
				};
				
				class EditBloom : RscEdit {
					idc = 1312;
					maxChars = 3;
					x = "16.2 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					y = "1.5 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
					w = "2.1 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					h = "1 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
				};
				
				class TextRadialBlur : TextBloom {
					idc = 1041;
					text = "$STR_A3_RscDisplayOptionsVideo_TextRadialBlur";
					x = "0 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					y = "3 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
					w = "8 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					h = "1 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
				};
				
				class ValueRadialBlur : RscXSliderH {
					idc = 1315;
					x = "8 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					y = "3 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
					w = "8 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					h = "1 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
				};
				
				class EditRadialBlur : RscEdit {
					idc = 1316;
					maxChars = 3;
					x = "16.2 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					y = "3 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
					w = "2.1 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					h = "1 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
				};
				
				class TextRotationBlur : TextBloom {
					idc = 1042;
					text = "$STR_A3_RscDisplayOptionsVideo_TextRotationBlur";
					x = "0 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					y = "4.5 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
					w = "8 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					h = "1 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
				};
				
				class ValueRotationBlur : RscXSliderH {
					idc = 1313;
					x = "8 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					y = "4.5 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
					w = "8 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					h = "1 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
				};
				
				class EditRotationBlur : RscEdit {
					idc = 1314;
					maxChars = 3;
					x = "16.2 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					y = "4.5 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
					w = "2.1 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					h = "1 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
				};
				
				class TextDOF : TextBloom {
					idc = 1044;
					text = "$STR_A3_RscDisplayOptionsVideo_TextDOF";
					x = "0 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					y = "6 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
					w = "8 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					h = "1 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
				};
				
				class ValueDOF : RscXSliderH {
					idc = 1317;
					x = "8 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					y = "6 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
					w = "8 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					h = "1 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
				};
				
				class EditDOF : RscEdit {
					idc = 1318;
					maxChars = 3;
					x = "16.2 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					y = "6 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
					w = "2.1 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					h = "1 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
				};
				
				class TextSSAO : TextBloom {
					idc = 1043;
					text = "$STR_A3_RscDisplayOptionsVideo_TextSSAO";
					x = "0 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					y = "7.5 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
					w = "8 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					h = "1 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
				};
				
				class ValueSSAO : RscCombo {
					idc = 1310;
					x = "8 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					y = "7.5 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
					w = "8 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					h = "1 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
					tooltip = "$STR_A3_RscDisplayOptionsVideo_ValueSSAO_tooltip";
				};
				
				class TextCaustics : TextBloom {
					idc = 1045;
					text = "$STR_A3_RscDisplayOptionsVideo_TextCaustics";
					x = "0 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					y = "9 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
					w = "8 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					h = "1 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
				};
				
				class ValueCaustics : RscCombo {
					idc = 1319;
					x = "8 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					y = "9 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
					w = "8 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					h = "1 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
					tooltip = "$STR_A3_RscDisplayOptionsVideo_ValueCaustics_tooltip";
				};
				
				class TextAntialias : RscText {
					style = 0;
					idc = 1035;
					text = "$STR_A3_RscDisplayOptionsVideo_TextAntialias";
					x = "21.5 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					y = "0 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
					w = "16.5 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					h = "1 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
					colorBackground[] = {0, 0, 0, 1};
				};
				
				class CA_TextAADetail : TextBloom {
					idc = 1020;
					text = "$STR_A3_RscDisplayOptionsVideo_CA_TextAADetail";
					x = "21.5 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					y = "1.5 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
					w = "8 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					h = "1 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
				};
				
				class CA_ValueAADetail : RscCombo {
					idc = 133;
					x = "29.5 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					y = "1.5 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
					w = "8 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					h = "1 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
					tooltip = "$STR_A3_RscDisplayOptionsVideo_CA_ValueAADetail_tooltip";
				};
				
				class CA_TextATOC : TextBloom {
					idc = 1027;
					text = "$STR_A3_RscDisplayOptionsVideo_CA_TextATOC";
					x = "21.5 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					y = "3 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
					w = "8 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					h = "1 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
				};
				
				class CA_ValueATOC : RscCombo {
					idc = 1300;
					wholeHeight = "8 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
					x = "29.5 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					y = "3 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
					w = "8 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					h = "1 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
					tooltip = "$STR_A3_RscDisplayOptionsVideo_CA_ValueATOC_tooltip";
				};
				
				class CA_TextFXAA : TextBloom {
					idc = 1024;
					text = "$STR_A3_RscDisplayOptionsVideo_CA_TextFXAA";
					x = "21.5 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					y = "4.5 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
					w = "8 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					h = "1 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
				};
				
				class CA_ValueFXAA : RscCombo {
					idc = 336;
					wholeHeight = "9 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
					x = "29.5 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					y = "4.5 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
					w = "8 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					h = "1 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
					tooltip = "$STR_A3_RscDisplayOptionsVideo_CA_ValueFXAA_tooltip";
				};
				
				class CA_TextAnisotropicDetail : TextBloom {
					idc = 1019;
					text = "$STR_A3_RscDisplayOptionsVideo_CA_TextAnisotropicDetail";
					x = "21.5 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					y = "6 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
					w = "8 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					h = "1 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
				};
				
				class CA_ValueAnisotropicDetail : RscCombo {
					idc = 130;
					x = "29.5 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					y = "6 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
					w = "8 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					h = "1 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
					tooltip = "$STR_A3_RscDisplayOptionsVideo_CA_ValueAnisotropicDetail_tooltip";
				};
			};
		};
	};
};
