// Generated by unRap v1.06 by Kegetys

class RscDisplayPublishMission {
	idd = 165;
	onLoad = "[""onLoad"",_this,""RscDisplayPublishMission"",'GUI'] call compile preprocessfilelinenumbers ""A3\ui_f\scripts\initDisplay.sqf""";
	onUnload = "[""onUnload"",_this,""RscDisplayPublishMission"",'GUI'] call compile preprocessfilelinenumbers ""A3\ui_f\scripts\initDisplay.sqf""";
	
	class controlsBackground {
		class FullscreenBackground : RscText {
			idc = -1;
			x = "SafezoneX";
			y = "SafezoneY";
			w = "SafezoneW";
			h = "SafezoneH";
			colorBackground[] = {0.7, 0.7, 0.7, 0.8};
		};
		
		class TitleBackground : RscText {
			colorBackground[] = {"(profilenamespace getvariable ['GUI_BCG_RGB_R',0.69])", "(profilenamespace getvariable ['GUI_BCG_RGB_G',0.75])", "(profilenamespace getvariable ['GUI_BCG_RGB_B',0.5])", "(profilenamespace getvariable ['GUI_BCG_RGB_A',0.8])"};
			idc = 1080;
			x = "1 * 			(			((safezoneW / safezoneH) min 1.2) / 40) + 			(safezoneX)";
			y = "SafezoneY + (1 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25))";
			w = "38 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
			h = "1 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
		};
		
		class ListBoxBackground : RscText {
			colorBackground[] = {0, 0, 0, 0.7};
			idc = 1081;
			x = "1 * 			(			((safezoneW / safezoneH) min 1.2) / 40) + 			(safezoneX)";
			y = "SafezoneY + (2.1 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25))";
			w = "12.5 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
			h = "20.8 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25) + (1 * (safezoneH - 			(			((safezoneW / safezoneH) min 1.2) / 1.2)))";
		};
		
		class RightBackground : RscText {
			colorBackground[] = {0, 0, 0, 0.7};
			idc = 1082;
			x = "13.6 * 			(			((safezoneW / safezoneH) min 1.2) / 40) + 			(safezoneX)";
			y = "SafezoneY + (2.1 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25))";
			w = "25.4 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
			h = "17.8 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25) + (1 * (safezoneH - 			(			((safezoneW / safezoneH) min 1.2) / 1.2)))";
		};
		
		class RightBottomBackground : RscText {
			colorBackground[] = {0, 0, 0, 0.7};
			idc = 1083;
			x = "13.6 * 			(			((safezoneW / safezoneH) min 1.2) / 40) + 			(safezoneX)";
			y = "SafezoneY + (20 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)) + (1 * (safezoneH - 			(			((safezoneW / safezoneH) min 1.2) / 1.2)))";
			w = "25.4 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
			h = "2.9 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
		};
	};
	
	class controls {
		class Background {};
		class ValueName {};
		class ButtonOK {};
		
		class Title : RscTitle {
			style = 0;
			y = "SafezoneY + (1 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25))";
			idc = 1000;
			text = "$STR_A3_RscDisplayPublishMission_Title";
			x = "1 * 			(			((safezoneW / safezoneH) min 1.2) / 40) + 			(safezoneX)";
			w = "20 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
			h = "1 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
		};
		
		class PlayersName : Title {
			style = 1;
			colorBackground[] = {0, 0, 0, 0};
			y = "SafezoneY + (1 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25))";
			idc = 1010;
			x = "21 * 			(			((safezoneW / safezoneH) min 1.2) / 40) + 			(safezoneX)";
			w = "18 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
			h = "1 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
		};
		
		class SteamScenarios : RscListBox {
			idc = 105;
			y = "SafezoneY + (2.3 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25))";
			h = "SafezoneH - (5 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25))";
			x = "1 * 			(			((safezoneW / safezoneH) min 1.2) / 40) + 			(safezoneX)";
			w = "12.5 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
			colorBackground[] = {0, 0, 0, 0};
		};
		
		class TextName : RscText {
			SizeEx = "(			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25) * 1)";
			shadow = false;
			style = 1;
			y = "SafezoneY + (2.3 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25))";
			idc = 1001;
			text = "$STR_A3_RscDisplayPublishMission_TextName";
			x = "13.9 * 			(			((safezoneW / safezoneH) min 1.2) / 40) + 			(safezoneX)";
			w = "6 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
			h = "1 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
		};
		
		class EditBoxName : RscEdit {
			idc = 101;
			maxChars = 45;
			y = "SafezoneY + (2.3 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25))";
			x = "20 * 			(			((safezoneW / safezoneH) min 1.2) / 40) + 			(safezoneX)";
			w = "12.5 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
			h = "1 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
			tooltip = "$STR_A3_RscDisplayPublishMission_EditBoxName_tooltip";
		};
		
		class TextTags : RscText {
			shadow = false;
			style = 1;
			y = "SafezoneY + (3.7 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25))";
			idc = 1002;
			text = "$STR_A3_RscDisplayPublishMission_TextTags";
			x = "13.9 * 			(			((safezoneW / safezoneH) min 1.2) / 40) + 			(safezoneX)";
			w = "6 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
			h = "1 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
		};
		
		class ValueTags : RscEdit {
			idc = 102;
			canModify = 0;
			y = "SafezoneY + (3.7 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25))";
			x = "20 * 			(			((safezoneW / safezoneH) min 1.2) / 40) + 			(safezoneX)";
			w = "12.5 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
			h = "1 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
			tooltip = "$STR_A3_RscDisplayPublishMission_ValueTags_tooltip";
		};
		
		class ButtonEditTags : RscButtonMenu {
			idc = 115;
			y = "SafezoneY + (3.7 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25))";
			text = "$STR_A3_RscDisplayPublishMission_ButtonEditTags";
			x = "32.6 * 			(			((safezoneW / safezoneH) min 1.2) / 40) + 			(safezoneX)";
			w = "6.25 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
			h = "1 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
		};
		
		class TextVisibility : RscText {
			shadow = false;
			style = 1;
			y = "SafezoneY + (5.1 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25))";
			idc = 1003;
			text = "$STR_A3_RscDisplayPublishMission_TextVisibility";
			x = "13.9 * 			(			((safezoneW / safezoneH) min 1.2) / 40) + 			(safezoneX)";
			w = "6 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
			h = "1 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
		};
		
		class ComboBoxVisibility : RscCombo {
			idc = 106;
			y = "SafezoneY + (5.1 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25))";
			x = "20 * 			(			((safezoneW / safezoneH) min 1.2) / 40) + 			(safezoneX)";
			w = "12.5 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
			h = "1 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
			tooltip = "$STR_A3_RscDisplayPublishMission_ComboBoxVisibility_tooltip";
		};
		
		class TextDescription : RscText {
			shadow = false;
			style = 1;
			y = "SafezoneY + (6.5 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25))";
			idc = 1004;
			text = "$STR_A3_RscDisplayPublishMission_TextDescription";
			x = "13.9 * 			(			((safezoneW / safezoneH) min 1.2) / 40) + 			(safezoneX)";
			w = "6 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
			h = "1 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
		};
		
		class ValueDescription : RscEdit {
			idc = 104;
			maxChars = 8000;
			style = 16;
			y = "SafezoneY + (6.5 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25))";
			h = "3 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25) + (0.5 * (safezoneH - 			(			((safezoneW / safezoneH) min 1.2) / 1.2)))";
			x = "20 * 			(			((safezoneW / safezoneH) min 1.2) / 40) + 			(safezoneX)";
			w = "12.5 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
			colorBackground[] = {0, 0, 0, 0.3};
			tooltip = "$STR_A3_RscDisplayPublishMission_ValueDescription_tooltip";
		};
		
		class ChangeNoteControlsGroup : RscControlsGroupNoScrollbars {
			idc = 121;
			y = "SafezoneY + (9.9 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)) + (0.5 * (safezoneH - 			(			((safezoneW / safezoneH) min 1.2) / 1.2)))";
			x = "13.9 * 			(			((safezoneW / safezoneH) min 1.2) / 40) + 			(safezoneX)";
			w = "18.7 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
			h = "2.2 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
			
			class controls {
				class TextChangeNotes : RscText {
					shadow = false;
					style = 1;
					idc = 1005;
					text = "$STR_A3_RscDisplayPublishMission_TextChangeNotes";
					x = "0 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					y = "0.1 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
					w = "6 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					h = "1 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
				};
				
				class ValueChangeNotes : RscEdit {
					idc = 107;
					maxChars = 5000;
					style = 16;
					x = "6.1 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					y = "0.1 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
					w = "12.5 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					h = "2 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
					tooltip = "$STR_A3_RscDisplayPublishMission_ValueChangeNotes_tooltip";
				};
			};
		};
		
		class OverviewPicture : RscPictureKeepAspect {
			idc = 108;
			y = "SafezoneY + (12.3 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)) + (0.5 * (safezoneH - 			(			((safezoneW / safezoneH) min 1.2) / 1.2)))";
			text = "\A3\Ui_f\data\GUI\Rsc\RscDisplayPublishMission\SteamWorksDefaultImage_co.paa";
			x = "20 * 			(			((safezoneW / safezoneH) min 1.2) / 40) + 			(safezoneX)";
			w = "12.5 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
			h = "6.25 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
			tooltip = $STR_A3_RSCDISPLAYPUBLISHMISSION_OVERVIEWPICTURE_TOOLTIP;
		};
		
		class ButtonSelectImage : RscButtonMenu {
			idc = 118;
			y = "SafezoneY + (18.65 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)) + (0.5 * (safezoneH - 			(			((safezoneW / safezoneH) min 1.2) / 1.2)))";
			text = "$STR_A3_RscDisplayPublishMission_ButtonSelectImage";
			x = "20 * 			(			((safezoneW / safezoneH) min 1.2) / 40) + 			(safezoneX)";
			w = "6 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
			h = "1 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
			tooltip = "$STR_A3_RscDisplayPublishMission_ButtonSelectImage_tooltip";
		};
		
		class ButtonDefaultImage : RscButtonMenu {
			idc = 119;
			y = "SafezoneY + (18.65 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)) + (0.5 * (safezoneH - 			(			((safezoneW / safezoneH) min 1.2) / 1.2)))";
			text = "$STR_A3_RscDisplayPublishMission_ButtonDefaultImage";
			x = "26.5 * 			(			((safezoneW / safezoneH) min 1.2) / 40) + 			(safezoneX)";
			w = "6 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
			h = "1 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
			tooltip = "$STR_A3_RscDisplayPublishMission_ButtonDefaultImage_tooltip";
		};
		
		class TextSteamQuota : RscText {
			shadow = false;
			style = 1;
			idc = 1012;
			text = "$STR_A3_RscDisplayPublishMission_TextSteamQuota";
			x = "13.9 * 			(			((safezoneW / safezoneH) min 1.2) / 40) + 			(safezoneX)";
			y = "20.2 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25) + 			(safezoneY + safezoneH - 			(			((safezoneW / safezoneH) min 1.2) / 1.2))";
			w = "9.2 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
			h = "1 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
		};
		
		class SliderStorageSpace : RscProgress {
			idc = 120;
			texture = "";
			textureExt = "";
			colorBar[] = {1, 1, 1, 1};
			colorExtBar[] = {1, 1, 1, 1};
			colorFrame[] = {0.5, 0.5, 0.5, 0.5};
			colorBackground[] = {0.5, 0.5, 0.5, 0.5};
			x = "23 * 			(			((safezoneW / safezoneH) min 1.2) / 40) + 			(safezoneX)";
			y = "20.2 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25) + 			(safezoneY + safezoneH - 			(			((safezoneW / safezoneH) min 1.2) / 1.2))";
			w = "9.5 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
			h = "1 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
			tooltip = "$STR_A3_RscDisplayPublishMission_SliderStorageSpace_tooltip";
		};
		
		class TextSteamQuotaValue : RscText {
			idc = 111;
			shadow = false;
			x = "32.5 * 			(			((safezoneW / safezoneH) min 1.2) / 40) + 			(safezoneX)";
			y = "20.2 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25) + 			(safezoneY + safezoneH - 			(			((safezoneW / safezoneH) min 1.2) / 1.2))";
			w = "6.3 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
			h = "1 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
		};
		
		class TextLicence : RscText {
			shadow = false;
			style = 1;
			idc = 1007;
			text = "$STR_A3_RscDisplayPublishMission_TextLicence";
			x = "13.9 * 			(			((safezoneW / safezoneH) min 1.2) / 40) + 			(safezoneX)";
			y = "21.7 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25) + 			(safezoneY + safezoneH - 			(			((safezoneW / safezoneH) min 1.2) / 1.2))";
			w = "9.2 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
			h = "1 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
		};
		
		class ButtonLicence : RscButtonMenu {
			idc = 117;
			style = 0;
			
			class Attributes {
				font = "PuristaMedium";
			};
			text = "$STR_A3_RscDisplayPublishMission_ButtonLicence";
			x = "23 * 			(			((safezoneW / safezoneH) min 1.2) / 40) + 			(safezoneX)";
			y = "21.7 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25) + 			(safezoneY + safezoneH - 			(			((safezoneW / safezoneH) min 1.2) / 1.2))";
			w = "9.5 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
			h = "1 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
			tooltip = "$STR_A3_RscDisplayPublishMission_ButtonLicence_tooltip";
		};
		
		class TextQuestionMark : RscText {
			shadow = false;
			idc = 1008;
			text = "$STR_A3_RscDisplayPublishMission_TextQuestionMark";
			x = "32.4 * 			(			((safezoneW / safezoneH) min 1.2) / 40) + 			(safezoneX)";
			y = "21.7 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25) + 			(safezoneY + safezoneH - 			(			((safezoneW / safezoneH) min 1.2) / 1.2))";
			w = "0.8 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
			h = "1 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
		};
		
		class CheckBoxLicence : RscTextCheckBox {
			idc = 109;
			sizeEx = "(			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25) * 1)";
			strings[] = {$STR_MSG_DISAGREE};
			checked_strings[] = {$STR_MSG_AGREE};
			colorSelectedBg[] = {0, 0, 0, 0};
			x = "33.3 * 			(			((safezoneW / safezoneH) min 1.2) / 40) + 			(safezoneX)";
			y = "21.7 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25) + 			(safezoneY + safezoneH - 			(			((safezoneW / safezoneH) min 1.2) / 1.2))";
			w = "5.5 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
			h = "1 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
			tooltip = "$STR_A3_RscDisplayPublishMission_CheckBoxLicence_tooltip";
		};
		
		class ButtonDoPublish : RscButtonMenu {
			idc = 112;
			text = "$STR_A3_RscDisplayPublishMission_ButtonDoPublish";
			x = "32.75 * 			(			((safezoneW / safezoneH) min 1.2) / 40) + 			(safezoneX)";
			y = "23 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25) + 			(safezoneY + safezoneH - 			(			((safezoneW / safezoneH) min 1.2) / 1.2))";
			w = "6.25 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
			h = "1 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
			tooltip = "$STR_A3_RscDisplayPublishMission_ButtonDoPublish_tooltip";
		};
		
		class ButtonDoUpdate : RscButtonMenu {
			idc = 113;
			text = "$STR_A3_RscDisplayPublishMission_ButtonDoUpdate";
			x = "32.75 * 			(			((safezoneW / safezoneH) min 1.2) / 40) + 			(safezoneX)";
			y = "23 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25) + 			(safezoneY + safezoneH - 			(			((safezoneW / safezoneH) min 1.2) / 1.2))";
			w = "6.25 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
			h = "1 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
			tooltip = "$STR_A3_RscDisplayPublishMission_ButtonDoUpdate_tooltip";
		};
		
		class ButtonCancel : RscButtonMenuCancel {
			x = "1 * 			(			((safezoneW / safezoneH) min 1.2) / 40) + 			(safezoneX)";
			y = "23 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25) + 			(safezoneY + safezoneH - 			(			((safezoneW / safezoneH) min 1.2) / 1.2))";
			w = "6.25 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
			h = "1 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
			tooltip = "$STR_A3_RscDisplayPublishMission_ButtonCancel_tooltip";
		};
		
		class ButtonDelete : RscButtonMenu {
			idc = 114;
			text = "$STR_A3_RscDisplayPublishMission_ButtonDelete";
			x = "26.4 * 			(			((safezoneW / safezoneH) min 1.2) / 40) + 			(safezoneX)";
			y = "23 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25) + 			(safezoneY + safezoneH - 			(			((safezoneW / safezoneH) min 1.2) / 1.2))";
			w = "6.25 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
			h = "1 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
			tooltip = "$STR_A3_RscDisplayPublishMission_ButtonDelete_tooltip";
		};
	};
};
