// Generated by unRap v1.06 by Kegetys

class RscDisplayLoadingBlack {
	idd = -1;
	enableSimulation = 0;
	
	class controls {
		class FadeEffect : RscText {
			idc = 1099;
			x = "safezoneXAbs";
			y = "safezoneY";
			w = "safezoneWAbs";
			h = "safezoneH";
			colorBackground[] = {0, 0, 0, 1};
		};
	};
};
