// Generated by unRap v1.06 by Kegetys

class RscDisplayCamera {
	onLoad = "[""onLoad"",_this,""RscDisplayCamera"",'GUI'] call compile preprocessfilelinenumbers ""A3\ui_f\scripts\initDisplay.sqf""";
	onUnload = "[""onUnload"",_this,""RscDisplayCamera"",'GUI'] call compile preprocessfilelinenumbers ""A3\ui_f\scripts\initDisplay.sqf""";
	idd = 314;
	movingEnable = 0;
	enableSimulation = 1;
	iconCamera = "\A3\ui_f\data\GUI\Rsc\RscDisplayMissionEditor\iconCamera_ca.paa";
	
	class ControlsBackground {
		class Map : RscMapControl {
			idc = 3141;
			x = -10;
			y = -10;
			w = "0.8 * safezoneW";
			h = "0.8 * safezoneH";
		};
		
		class Overlay : RscControlsGroup {
			idc = 3142;
			x = "safezoneX";
			y = "safezoneY";
			w = "safezoneW";
			h = "safezoneH";
			
			class VScrollbar : VScrollbar {
				width = 0;
			};
			
			class HScrollbar : HScrollbar {
				height = 0;
			};
			
			class Controls {
				class Header : RscText {
					colorText[] = {1, 1, 1, 1};
					colorBackground[] = {0, 0, 0, 0};
					x = 0;
					y = 0;
					w = "safezoneW";
					h = "1.5 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
					text = "$STR_A3_RscDisplayCamera_Header";
					font = "PuristaLight";
					sizeEx = "1.5 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
					shadow = true;
				};
				
				class SubHeader : Header {
					x = 0;
					y = "1.5 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
					w = "safezoneW";
					h = "14 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
					text = "$STR_A3_RscDisplayCamera_SubHeader";
					sizeEx = "0.8 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
					style = 16;
				};
				
				class Debug : Header {
					idc = 31420;
					x = 0;
					y = "safezoneH - 8 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
					h = "8 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
					text = "";
					sizeEx = "0.8 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
					shadow = true;
					style = 16;
				};
				
				class Positions : Header {
					idc = 31422;
					x = "safezoneW - 0.2";
					y = 0;
					h = "10 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
					w = 0.2;
					text = "";
					sizeEx = "0.8 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
					shadow = true;
					style = 16;
				};
				
				class Unit : RscFrame {
					colorText[] = {1, 1, 1, 1};
					idc = 31421;
					x = -10;
					y = -10;
					w = 0;
					h = 0;
				};
				
				class LineHorizontalTop : RscText {
					colorBackground[] = {0.75, 0.75, 0.75, 0.75};
					x = 0;
					y = "0.33 * safezoneH";
					w = "safezoneW";
					h = "0.001 * safezoneH";
				};
				
				class LineHorizontalBottom : LineHorizontalTop {
					x = 0;
					y = "0.66 * safezoneH";
					w = "safezoneW";
					h = "0.001 * safezoneH";
				};
				
				class LineVerticalLeft : LineHorizontalTop {
					x = "0.66 * safezoneW";
					y = 0;
					w = "0.001 * safezoneH";
					h = "safezoneH";
				};
				
				class LineVerticalRight : LineHorizontalTop {
					x = "0.33 * safezoneW";
					y = 0;
					w = "0.001 * safezoneH";
					h = "safezoneH";
				};
				
				class CrossHorizontal : LineHorizontalTop {
					x = "(safezoneW / 2) - (0.1 / 2)";
					y = "(safezoneH / 2)";
					w = 0.1;
					h = "0.001 * safezoneH";
				};
				
				class CrossVertical : LineHorizontalTop {
					x = "(safezoneW / 2)";
					y = "(safezoneH / 2) - (0.1 / 2)";
					w = "0.001 * safezoneH";
					h = 0.1;
				};
			};
		};
		
		class MouseArea : RscText {
			idc = 3140;
			style = 16;
			x = "safezoneX";
			y = "safezoneY";
			w = "safezoneW";
			h = "safezoneH";
		};
	};
	
	class Controls {
		class Overlay : RscControlsGroup {
			idc = 3143;
			x = "safezoneX + safezoneW - 13 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
			y = "safezoneY + safezoneH - 5 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
			w = "13 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
			h = "5 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
			
			class VScrollbar : VScrollbar {
				width = 0;
			};
			
			class HScrollbar : HScrollbar {
				height = 0;
			};
			
			class Controls {
				class TextFocus : RscText {
					x = 0;
					y = 0;
					w = "3 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					h = "1 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
					text = "$STR_A3_RscDisplayCamera_TextFocus";
					style = 0;
					sizeEx = "0.8 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
					font = "PuristaLight";
					shadow = true;
				};
				
				class SliderFocus : RscXSliderH {
					idc = 31430;
					x = "3 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					y = 0;
					w = "10 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					h = "0.8 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
					color[] = {1, 1, 1, 0.4};
					colorActive[] = {1, 1, 1, 0.6};
					arrowEmpty = "\A3\ui_f\data\gui\cfg\slider\arrowEmpty_ca.paa";
					arrowFull = "\A3\ui_f\data\gui\cfg\slider\arrowFull_ca.paa";
					border = "#(argb,8,8,3)color(0,0,0,0.1)";
					thumb = "#(argb,8,8,3)color(1,1,1,1)";
				};
				
				class ValueFocus : TextFocus {
					idc = 31431;
					x = "3 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					w = "10 * 			(			((safezoneW / safezoneH) min 1.2) / 40)";
					text = "0";
					style = 2;
					colorText[] = {1, 1, 1, 1};
				};
				
				class TextAperture : TextFocus {
					y = "1 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
					text = "$STR_A3_RscDisplayCamera_TextAperture";
				};
				
				class SliderAperture : SliderFocus {
					idc = 31432;
					y = "1 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
				};
				
				class ValueAperture : ValueFocus {
					idc = 31433;
					y = "1 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
				};
				
				class TextDaytime : TextFocus {
					y = "2 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
					text = "$STR_A3_RscDisplayCamera_TextDaytime";
				};
				
				class SliderDaytime : SliderFocus {
					idc = 31434;
					y = "2 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
				};
				
				class ValueDaytime : ValueFocus {
					idc = 31435;
					y = "2 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
				};
				
				class TextOvercast : TextFocus {
					y = "3 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
					text = "$STR_A3_RscDisplayCamera_TextOvercast";
				};
				
				class SliderOvercast : SliderFocus {
					idc = 31436;
					y = "3 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
				};
				
				class ValueOvercast : ValueFocus {
					idc = 31437;
					y = "3 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
				};
				
				class TextAcctime : TextFocus {
					y = "4 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
					text = "$STR_A3_RscDisplayCamera_TextAcctime";
				};
				
				class SliderAcctime : SliderFocus {
					idc = 31438;
					y = "4 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
				};
				
				class ValueAcctime : ValueFocus {
					idc = 31439;
					y = "4 * 			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
				};
			};
		};
	};
};
